In [1]:
import utils.dataset_utils as dataset
import utils.train_utils as train

import numpy as np
import copy
import pickle

from sklearn.base import BaseEstimator, ClassifierMixin
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from datetime import datetime
from dateutil.relativedelta import relativedelta

In [2]:
def unit_vector_norm(X):
    return (X.T / np.sqrt((X**2).sum(axis=1))).T

In [3]:
file_location = "../data/Raman_Mouse/preprocess/"
filenames = np.load(f"{file_location}FileNames.npy")
with open(f'{file_location}Sample_labels.pickle', 'rb') as f:
    labels = pickle.load(f)

data = []
for f in filenames:
    x = np.load(f"{file_location}{f.split('.')[0]}_raman.npy")
    data.append((unit_vector_norm(x.reshape(-1,x.shape[-1])).reshape(x.shape), labels[f]))


In [4]:
class MLP(nn.Module):
    def __init__(self, size=1300*7*7 , output=10, depth=2, neurons=1300, bias=True, **kwargs):
        super().__init__()

        self.layers = nn.Sequential( 
            nn.Dropout3d(0.25),
            nn.Flatten(),
            nn.Linear(size, neurons, bias=bias),
            nn.ReLU(True),
            *((nn.Linear(neurons, neurons, bias=bias),
            nn.ReLU(True)) * (depth-1)),
            nn.Linear(neurons, output, bias=bias)
        )
  
    def forward(self, x):
        return self.layers(x)

In [5]:
class SupervisedClassifier(BaseEstimator):
    def __init__(self, **kwargs):
        self.kwargs = kwargs

        _use_cuda = torch.cuda.is_available() and kwargs['cuda']
        if _use_cuda:
            torch.backends.cudnn.enabled = True
            torch.backends.cudnn.benchmark = True
        self.device = torch.device('cuda' if _use_cuda else 'cpu')        
        
    def fit(self, data):
        self.model = MLP(**self.kwargs).to(self.device)

        parameters = filter(lambda x: x.requires_grad, self.model.parameters())
        self.optimizer = optim.Adam(parameters)        
        train_loader, test_loader = dataset.load_liver(data, self.kwargs['batch_size'], self.kwargs['patch_size'])
        
        for epoch in range(self.kwargs['epochs']):
            print('-'*50)
            print('Epoch {:3d}/{:3d}'.format(epoch+1, self.kwargs['epochs']))
            start_time = datetime.now()
            train.train(self.model, self.optimizer, train_loader, self.kwargs['loss_func'], self.kwargs['log_step'], self.device)
            end_time = datetime.now()
            time_diff = relativedelta(end_time, start_time)
            print('Elapsed time: {}h {}m {}s'.format(time_diff.hours, time_diff.minutes, time_diff.seconds))
            loss = train.test(self.model, test_loader, self.kwargs['loss_func'], self.device)
            print('Validation| bits: {:2.2f}'.format(loss), flush=True)    
                         
        return self
    
    def predict(self, X):
        """
        predict transforms the data into the reference space. Min weight should be 0 or higher then 'min_weight'
        The error is the NMSE, where the MSE is normalised by the signal strength. 
        error.shape = X.shape[0], so for each data point the error is calculated.
        """
        # Check is fit had been called
        check_is_fitted(self)

        # Input validation
        X = check_array(X)
#         self.model(X)
        
#         return RCA_vector

In [6]:
BATCH_SIZE = 64
EPOCHS = 10
PATCH_SIZE = 7

kwargs = {'size': PATCH_SIZE*PATCH_SIZE*data[0][0].shape[-1],
          'batch_size': BATCH_SIZE,
          'patch_size': PATCH_SIZE,
          'cuda': False,
          'log_step': 30,
          'epochs': 20,
          'depth': 3,
          'output': 4,
          'loss_func': nn.BCEWithLogitsLoss(),
          'neurons': data[0][0].shape[-1],
          'bias': True
         }

In [7]:
rvc = SupervisedClassifier(**kwargs)
rvc.fit(data)


--------------------------------------------------
Epoch   1/ 20
tensor([[-0.0312, -0.0219,  0.0256,  0.0134],
        [-0.0320, -0.0222,  0.0227,  0.0134],
        [-0.0324, -0.0221,  0.0222,  0.0127],
        [-0.0318, -0.0231,  0.0252,  0.0139],
        [-0.0325, -0.0222,  0.0225,  0.0134],
        [-0.0325, -0.0227,  0.0226,  0.0134],
        [-0.0312, -0.0219,  0.0256,  0.0134],
        [-0.0320, -0.0223,  0.0228,  0.0133],
        [-0.0312, -0.0219,  0.0256,  0.0134],
        [-0.0322, -0.0224,  0.0225,  0.0130],
        [-0.0319, -0.0222,  0.0228,  0.0132],
        [-0.0326, -0.0229,  0.0249,  0.0140],
        [-0.0323, -0.0222,  0.0227,  0.0135],
        [-0.0312, -0.0219,  0.0256,  0.0134],
        [-0.0322, -0.0224,  0.0225,  0.0131],
        [-0.0326, -0.0231,  0.0244,  0.0138],
        [-0.0322, -0.0224,  0.0225,  0.0132],
        [-0.0324, -0.0231,  0.0249,  0.0136],
        [-0.0324, -0.0228,  0.0246,  0.0132],
        [-0.0323, -0.0229,  0.0251,  0.0136],
        [-0.032

tensor([[0.0889, 0.0750, 0.1054, 0.0871],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [7.7969, 4.4197, 5.7475, 5.0401],
        [7.8118, 4.4270, 5.7565, 5.0496],
        [7.8470, 4.6005, 5.9234, 5.0869],
        [7.7788, 4.5599, 5.8721, 5.0426],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [7.5344, 4.2756, 5.5593, 4.8844],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [7.4039, 4.3433, 5.5934, 4.8026],
        [7.0188, 4.1175, 5.3066, 4.5525],
        [8.0098, 4.5473, 5.9089, 5.1920],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [8.2575, 4.6824, 6.0826, 5.3504],
        [7.9839, 4.5248, 5.8831, 5.1607],
        [8.3033, 4.7145, 6.1247, 5.3779],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [8.0674, 4.5735, 5.9450, 5.2182],
        [7.8547, 4.4532, 5.7901, 5.0798],
        [9.1910, 5.2202, 6.7733, 5.9555],
        [0.0889, 0.0750, 0.1054, 0.0871],
        [6.9851, 4.0987, 5.2821, 4.5305],
        [0.0889, 0.0750, 0.1054, 0

tensor([[62.7948, 38.1566, 47.9348, 41.1528],
        [60.8636, 36.7528, 46.2205, 39.8843],
        [59.1350, 35.7095, 44.9115, 38.7457],
        [ 0.2377,  0.1848,  0.2246,  0.1851],
        [63.8133, 38.5335, 48.4563, 41.8155],
        [59.0623, 35.6652, 44.8559, 38.6981],
        [65.8169, 39.7602, 49.9922, 43.1359],
        [ 0.2377,  0.1848,  0.2246,  0.1851],
        [62.4197, 37.6929, 47.3997, 40.9025],
        [54.7323, 33.2699, 41.7975, 35.8745],
        [63.6987, 38.4658, 48.3712, 41.7405],
        [66.4362, 40.3574, 50.7045, 43.5289],
        [64.0624, 38.6819, 48.6428, 41.9776],
        [68.8533, 41.8245, 52.5449, 45.1285],
        [64.2678, 38.8015, 48.7971, 42.0936],
        [61.2592, 37.2260, 46.7667, 40.1482],
        [60.4183, 36.7200, 46.1297, 39.5988],
        [62.6716, 37.8402, 47.5880, 41.0662],
        [66.6082, 40.4612, 50.8345, 43.6388],
        [57.6638, 34.8221, 43.7948, 37.7833],
        [67.5750, 40.8035, 51.3082, 44.2774],
        [57.5925, 34.7771, 43.7399

tensor([[259.0167, 165.3700, 198.2286, 174.3001],
        [  0.5821,   0.4200,   0.4989,   0.4204],
        [261.5109, 166.9745, 200.1476, 175.9965],
        [  0.5821,   0.4200,   0.4989,   0.4204],
        [276.3591, 176.4507, 211.5096, 185.9797],
        [  0.5821,   0.4200,   0.4989,   0.4204],
        [268.9812, 171.7274, 205.8513, 180.9963],
        [279.5246, 178.7825, 214.2788, 188.0629],
        [258.9549, 165.3373, 198.1900, 174.2741],
        [243.7933, 155.6561, 186.5923, 164.0684],
        [  0.5821,   0.4200,   0.4989,   0.4204],
        [263.1652, 168.0228, 201.4089, 177.1045],
        [238.0919, 152.0168, 182.2275, 160.2357],
        [252.9657, 161.8168, 193.9427, 170.1959],
        [259.2060, 165.5012, 198.3850, 174.4444],
        [  0.5821,   0.4200,   0.4989,   0.4204],
        [241.9175, 154.4594, 185.1563, 162.8080],
        [259.6564, 165.7849, 198.7278, 174.7455],
        [270.9294, 172.9889, 207.3580, 182.3314],
        [256.2338, 163.9080, 196.4486, 172.3953],


tensor([[7.0168e+02, 4.8400e+02, 5.4427e+02, 4.9501e+02],
        [8.2603e+02, 5.6945e+02, 6.4024e+02, 5.8283e+02],
        [8.1111e+02, 5.5945e+02, 6.2911e+02, 5.7223e+02],
        [8.9901e+02, 6.2006e+02, 6.9726e+02, 6.3425e+02],
        [1.3228e+00, 9.6563e-01, 1.0837e+00, 9.6171e-01],
        [7.9045e+02, 5.4492e+02, 6.1267e+02, 5.5773e+02],
        [1.3228e+00, 9.6563e-01, 1.0837e+00, 9.6171e-01],
        [1.3228e+00, 9.6563e-01, 1.0837e+00, 9.6171e-01],
        [8.8428e+02, 6.0991e+02, 6.8585e+02, 6.2384e+02],
        [1.0730e+03, 7.3998e+02, 8.3206e+02, 7.5706e+02],
        [7.4541e+02, 5.1415e+02, 5.7818e+02, 5.2586e+02],
        [7.1566e+02, 4.9364e+02, 5.5511e+02, 5.0488e+02],
        [1.3228e+00, 9.6563e-01, 1.0837e+00, 9.6171e-01],
        [8.2269e+02, 5.6715e+02, 6.3766e+02, 5.8046e+02],
        [7.9032e+02, 5.4481e+02, 6.1255e+02, 5.5761e+02],
        [7.7980e+02, 5.3786e+02, 6.0485e+02, 5.5010e+02],
        [8.5666e+02, 5.9056e+02, 6.6398e+02, 6.0444e+02],
        [7.412

tensor([[1.8496e+03, 1.3621e+03, 1.4714e+03, 1.3309e+03],
        [2.8426e+00, 2.1527e+00, 2.3199e+00, 2.0738e+00],
        [1.8679e+03, 1.3757e+03, 1.4860e+03, 1.3442e+03],
        [2.8426e+00, 2.1527e+00, 2.3199e+00, 2.0738e+00],
        [2.0375e+03, 1.5002e+03, 1.6203e+03, 1.4662e+03],
        [2.8426e+00, 2.1527e+00, 2.3199e+00, 2.0738e+00],
        [1.8718e+03, 1.3785e+03, 1.4890e+03, 1.3469e+03],
        [2.0153e+03, 1.4839e+03, 1.6027e+03, 1.4502e+03],
        [2.0467e+03, 1.5073e+03, 1.6282e+03, 1.4728e+03],
        [1.9407e+03, 1.4289e+03, 1.5434e+03, 1.3965e+03],
        [1.8079e+03, 1.3312e+03, 1.4378e+03, 1.3010e+03],
        [1.8918e+03, 1.3933e+03, 1.5050e+03, 1.3614e+03],
        [1.7671e+03, 1.3014e+03, 1.4058e+03, 1.2716e+03],
        [2.3007e+03, 1.6941e+03, 1.8297e+03, 1.6556e+03],
        [1.8946e+03, 1.3950e+03, 1.5067e+03, 1.3634e+03],
        [2.8426e+00, 2.1527e+00, 2.3199e+00, 2.0738e+00],
        [1.9910e+03, 1.4662e+03, 1.5838e+03, 1.4327e+03],
        [2.842

tensor([[3.8973e+03, 3.0124e+03, 3.2038e+03, 2.8835e+03],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [4.0941e+03, 3.1645e+03, 3.3656e+03, 3.0291e+03],
        [4.0468e+03, 3.1277e+03, 3.3263e+03, 2.9941e+03],
        [3.9131e+03, 3.0246e+03, 3.2169e+03, 2.8952e+03],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [4.2598e+03, 3.2923e+03, 3.5014e+03, 3.1517e+03],
        [4.7026e+03, 3.6348e+03, 3.8658e+03, 3.4793e+03],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [3.9210e+03, 3.0304e+03, 3.2229e+03, 2.9010e+03],
        [4.1054e+03, 3.1732e+03, 3.3749e+03, 3.0375e+03],
        [5.6676e+00, 4.4422e+00, 4.7182e+00, 4.2211e+00],
        [4.2842e+03, 3.3114e+03, 3.5218e+03, 3.1698e+03],
        [3.911

tensor([[8.5294e+03, 6.8038e+03, 7.2438e+03, 6.5440e+03],
        [8.0121e+03, 6.3911e+03, 6.8045e+03, 6.1471e+03],
        [1.0518e+01, 8.4554e+00, 8.9916e+00, 8.0959e+00],
        [7.6863e+03, 6.1310e+03, 6.5274e+03, 5.8971e+03],
        [8.4632e+03, 6.7507e+03, 7.1871e+03, 6.4931e+03],
        [7.3869e+03, 5.8921e+03, 6.2731e+03, 5.6673e+03],
        [1.0518e+01, 8.4554e+00, 8.9916e+00, 8.0959e+00],
        [8.1099e+03, 6.4689e+03, 6.8871e+03, 6.2221e+03],
        [7.7342e+03, 6.1692e+03, 6.5680e+03, 5.9338e+03],
        [8.9846e+03, 7.1666e+03, 7.6299e+03, 6.8931e+03],
        [8.4869e+03, 6.7696e+03, 7.2072e+03, 6.5113e+03],
        [9.9619e+03, 7.9461e+03, 8.4598e+03, 7.6429e+03],
        [1.0518e+01, 8.4554e+00, 8.9916e+00, 8.0959e+00],
        [8.7330e+03, 6.9658e+03, 7.4161e+03, 6.7000e+03],
        [8.6539e+03, 6.9028e+03, 7.3490e+03, 6.6394e+03],
        [8.0004e+03, 6.3818e+03, 6.7946e+03, 6.1381e+03],
        [8.0571e+03, 6.4268e+03, 6.8423e+03, 6.1816e+03],
        [7.636

tensor([[1.6859e+04, 1.3778e+04, 1.4657e+04, 1.3306e+04],
        [1.5471e+04, 1.2644e+04, 1.3450e+04, 1.2211e+04],
        [1.5594e+04, 1.2745e+04, 1.3557e+04, 1.2308e+04],
        [1.4419e+04, 1.1785e+04, 1.2536e+04, 1.1381e+04],
        [1.8457e+01, 1.5152e+01, 1.6105e+01, 1.4590e+01],
        [1.8457e+01, 1.5152e+01, 1.6105e+01, 1.4590e+01],
        [1.8457e+01, 1.5152e+01, 1.6105e+01, 1.4590e+01],
        [1.4709e+04, 1.2021e+04, 1.2788e+04, 1.1609e+04],
        [1.6743e+04, 1.3683e+04, 1.4556e+04, 1.3215e+04],
        [1.5618e+04, 1.2764e+04, 1.3578e+04, 1.2327e+04],
        [1.3680e+04, 1.1180e+04, 1.1893e+04, 1.0797e+04],
        [1.4548e+04, 1.1890e+04, 1.2648e+04, 1.1482e+04],
        [1.4868e+04, 1.2152e+04, 1.2927e+04, 1.1735e+04],
        [1.7017e+04, 1.3907e+04, 1.4794e+04, 1.3431e+04],
        [1.4056e+04, 1.1488e+04, 1.2221e+04, 1.1094e+04],
        [1.3735e+04, 1.1225e+04, 1.1941e+04, 1.0840e+04],
        [1.4840e+04, 1.2129e+04, 1.2902e+04, 1.1713e+04],
        [1.549

tensor([[2.6123e+04, 2.1758e+04, 2.3130e+04, 2.1145e+04],
        [2.6799e+04, 2.2321e+04, 2.3728e+04, 2.1693e+04],
        [2.9837e+04, 2.4852e+04, 2.6419e+04, 2.4152e+04],
        [3.1179e+01, 2.6041e+01, 2.7670e+01, 2.5262e+01],
        [2.7643e+04, 2.3024e+04, 2.4476e+04, 2.2376e+04],
        [2.6839e+04, 2.2355e+04, 2.3764e+04, 2.1725e+04],
        [3.1179e+01, 2.6041e+01, 2.7670e+01, 2.5262e+01],
        [2.8756e+04, 2.3952e+04, 2.5461e+04, 2.3277e+04],
        [2.7642e+04, 2.3024e+04, 2.4475e+04, 2.2375e+04],
        [2.8154e+04, 2.3450e+04, 2.4928e+04, 2.2790e+04],
        [3.1179e+01, 2.6041e+01, 2.7670e+01, 2.5262e+01],
        [2.6016e+04, 2.1669e+04, 2.3035e+04, 2.1059e+04],
        [2.7357e+04, 2.2786e+04, 2.4223e+04, 2.2144e+04],
        [3.1179e+01, 2.6041e+01, 2.7670e+01, 2.5262e+01],
        [3.1179e+01, 2.6041e+01, 2.7670e+01, 2.5262e+01],
        [2.7224e+04, 2.2676e+04, 2.4105e+04, 2.2037e+04],
        [2.4696e+04, 2.0569e+04, 2.1866e+04, 1.9990e+04],
        [3.117

tensor([[4.2425e+04, 3.6047e+04, 3.8157e+04, 3.5175e+04],
        [3.8240e+04, 3.2491e+04, 3.4392e+04, 3.1705e+04],
        [4.4999e+04, 3.8234e+04, 4.0471e+04, 3.7309e+04],
        [4.4173e+04, 3.7532e+04, 3.9728e+04, 3.6624e+04],
        [5.0692e+01, 4.3144e+01, 4.5654e+01, 4.2055e+01],
        [5.0692e+01, 4.3144e+01, 4.5654e+01, 4.2055e+01],
        [5.0692e+01, 4.3144e+01, 4.5654e+01, 4.2055e+01],
        [4.8443e+04, 4.1161e+04, 4.3570e+04, 4.0165e+04],
        [3.9684e+04, 3.3718e+04, 3.5691e+04, 3.2902e+04],
        [4.1529e+04, 3.5286e+04, 3.7351e+04, 3.4433e+04],
        [4.2306e+04, 3.5946e+04, 3.8050e+04, 3.5077e+04],
        [4.5974e+04, 3.9063e+04, 4.1349e+04, 3.8118e+04],
        [4.4814e+04, 3.8077e+04, 4.0305e+04, 3.7156e+04],
        [4.3228e+04, 3.6729e+04, 3.8879e+04, 3.5841e+04],
        [4.1558e+04, 3.5311e+04, 3.7377e+04, 3.4457e+04],
        [4.9189e+04, 4.1795e+04, 4.4240e+04, 4.0784e+04],
        [4.2407e+04, 3.6032e+04, 3.8140e+04, 3.5160e+04],
        [4.661

tensor([[6.4816e+04, 5.6061e+04, 5.9249e+04, 5.4913e+04],
        [7.9584e+01, 6.8911e+01, 7.2813e+01, 6.7454e+01],
        [6.1975e+04, 5.3604e+04, 5.6653e+04, 5.2506e+04],
        [6.9681e+04, 6.0269e+04, 6.3697e+04, 5.9035e+04],
        [6.3035e+04, 5.4521e+04, 5.7622e+04, 5.3405e+04],
        [6.4835e+04, 5.6077e+04, 5.9266e+04, 5.4929e+04],
        [7.9584e+01, 6.8911e+01, 7.2813e+01, 6.7454e+01],
        [7.1225e+04, 6.1604e+04, 6.5108e+04, 6.0344e+04],
        [6.5970e+04, 5.7059e+04, 6.0304e+04, 5.5891e+04],
        [7.9584e+01, 6.8911e+01, 7.2813e+01, 6.7454e+01],
        [6.8580e+04, 5.9316e+04, 6.2690e+04, 5.8102e+04],
        [7.5997e+04, 6.5731e+04, 6.9469e+04, 6.4386e+04],
        [7.1132e+04, 6.1523e+04, 6.5023e+04, 6.0264e+04],
        [6.7922e+04, 5.8747e+04, 6.2089e+04, 5.7545e+04],
        [7.9584e+01, 6.8911e+01, 7.2813e+01, 6.7454e+01],
        [6.1143e+04, 5.2884e+04, 5.5892e+04, 5.1801e+04],
        [7.9584e+01, 6.8911e+01, 7.2813e+01, 6.7454e+01],
        [6.122

tensor([[1.2177e+02, 1.0711e+02, 1.1286e+02, 1.0499e+02],
        [1.2177e+02, 1.0711e+02, 1.1286e+02, 1.0499e+02],
        [1.1045e+05, 9.7078e+04, 1.0230e+05, 9.5194e+04],
        [1.0590e+05, 9.3079e+04, 9.8088e+04, 9.1272e+04],
        [1.0495e+05, 9.2247e+04, 9.7211e+04, 9.0456e+04],
        [9.5013e+04, 8.3511e+04, 8.8006e+04, 8.1889e+04],
        [1.0631e+05, 9.3441e+04, 9.8470e+04, 9.1627e+04],
        [1.0837e+05, 9.5251e+04, 1.0038e+05, 9.3401e+04],
        [1.0432e+05, 9.1694e+04, 9.6629e+04, 8.9914e+04],
        [1.0746e+05, 9.4450e+04, 9.9533e+04, 9.2616e+04],
        [9.8280e+04, 8.6383e+04, 9.1032e+04, 8.4705e+04],
        [1.2177e+02, 1.0711e+02, 1.1286e+02, 1.0499e+02],
        [1.0591e+05, 9.3093e+04, 9.8103e+04, 9.1285e+04],
        [1.0127e+05, 8.9014e+04, 9.3805e+04, 8.7285e+04],
        [1.0267e+05, 9.0238e+04, 9.5094e+04, 8.8485e+04],
        [1.1419e+05, 1.0036e+05, 1.0576e+05, 9.8414e+04],
        [1.2141e+05, 1.0671e+05, 1.1246e+05, 1.0464e+05],
        [1.057

tensor([[1.7386e+05, 1.5505e+05, 1.6222e+05, 1.5172e+05],
        [1.5962e+05, 1.4236e+05, 1.4894e+05, 1.3930e+05],
        [1.5552e+05, 1.3870e+05, 1.4511e+05, 1.3571e+05],
        [1.5715e+05, 1.4015e+05, 1.4663e+05, 1.3714e+05],
        [1.6141e+05, 1.4395e+05, 1.5060e+05, 1.4085e+05],
        [1.6491e+05, 1.4707e+05, 1.5387e+05, 1.4391e+05],
        [1.5706e+05, 1.4007e+05, 1.4655e+05, 1.3706e+05],
        [1.7129e+05, 1.5276e+05, 1.5982e+05, 1.4947e+05],
        [1.5478e+05, 1.3803e+05, 1.4441e+05, 1.3507e+05],
        [1.5284e+05, 1.3631e+05, 1.4261e+05, 1.3338e+05],
        [1.6336e+05, 1.4569e+05, 1.5242e+05, 1.4256e+05],
        [1.5943e+05, 1.4218e+05, 1.4875e+05, 1.3912e+05],
        [1.6705e+05, 1.4898e+05, 1.5586e+05, 1.4577e+05],
        [1.6957e+05, 1.5123e+05, 1.5822e+05, 1.4798e+05],
        [1.5921e+05, 1.4199e+05, 1.4855e+05, 1.3893e+05],
        [1.8167e+02, 1.6210e+02, 1.6958e+02, 1.5857e+02],
        [1.6555e+05, 1.4764e+05, 1.5447e+05, 1.4447e+05],
        [1.715

tensor([[2.7904e+05, 2.5175e+05, 2.6207e+05, 2.4665e+05],
        [2.5491e+05, 2.2997e+05, 2.3940e+05, 2.2531e+05],
        [2.6497e+02, 2.3914e+02, 2.4892e+02, 2.3425e+02],
        [2.2565e+05, 2.0358e+05, 2.1193e+05, 1.9945e+05],
        [2.5000e+05, 2.2555e+05, 2.3480e+05, 2.2098e+05],
        [2.3157e+05, 2.0892e+05, 2.1748e+05, 2.0469e+05],
        [2.4337e+05, 2.1956e+05, 2.2856e+05, 2.1511e+05],
        [2.4402e+05, 2.2016e+05, 2.2918e+05, 2.1569e+05],
        [2.1179e+05, 1.9107e+05, 1.9891e+05, 1.8720e+05],
        [2.6497e+02, 2.3914e+02, 2.4892e+02, 2.3425e+02],
        [2.6497e+02, 2.3914e+02, 2.4892e+02, 2.3425e+02],
        [2.1422e+05, 1.9327e+05, 2.0119e+05, 1.8935e+05],
        [2.6497e+02, 2.3914e+02, 2.4892e+02, 2.3425e+02],
        [2.4587e+05, 2.2182e+05, 2.3091e+05, 2.1732e+05],
        [2.6497e+02, 2.3914e+02, 2.4892e+02, 2.3425e+02],
        [2.8186e+05, 2.5429e+05, 2.6471e+05, 2.4913e+05],
        [2.6497e+02, 2.3914e+02, 2.4892e+02, 2.3425e+02],
        [2.651

tensor([[3.1519e+05, 2.8748e+05, 2.9791e+05, 2.8191e+05],
        [3.2749e+05, 2.9870e+05, 3.0954e+05, 2.9291e+05],
        [3.4120e+05, 3.1120e+05, 3.2250e+05, 3.0518e+05],
        [3.1301e+05, 2.8550e+05, 2.9585e+05, 2.7997e+05],
        [3.6968e+05, 3.3718e+05, 3.4941e+05, 3.3065e+05],
        [3.6239e+05, 3.3053e+05, 3.4252e+05, 3.2413e+05],
        [3.7959e+02, 3.4631e+02, 3.5885e+02, 3.3955e+02],
        [3.2649e+05, 2.9779e+05, 3.0859e+05, 2.9202e+05],
        [3.1780e+05, 2.8986e+05, 3.0038e+05, 2.8425e+05],
        [3.3961e+05, 3.0975e+05, 3.2099e+05, 3.0375e+05],
        [3.6455e+05, 3.3251e+05, 3.4457e+05, 3.2607e+05],
        [3.4413e+05, 3.1388e+05, 3.2527e+05, 3.0780e+05],
        [3.3387e+05, 3.0452e+05, 3.1557e+05, 2.9862e+05],
        [3.7959e+02, 3.4631e+02, 3.5885e+02, 3.3955e+02],
        [3.7959e+02, 3.4631e+02, 3.5885e+02, 3.3955e+02],
        [3.7471e+05, 3.4176e+05, 3.5416e+05, 3.3514e+05],
        [3.3108e+05, 3.0198e+05, 3.1293e+05, 2.9613e+05],
        [3.316

tensor([[5.3337e+02, 4.9175e+02, 5.0795e+02, 4.8180e+02],
        [5.7724e+05, 5.3211e+05, 5.4966e+05, 5.2139e+05],
        [4.9967e+05, 4.6059e+05, 4.7579e+05, 4.5132e+05],
        [5.3337e+02, 4.9175e+02, 5.0795e+02, 4.8180e+02],
        [5.3337e+02, 4.9175e+02, 5.0795e+02, 4.8180e+02],
        [5.3706e+05, 4.9507e+05, 5.1140e+05, 4.8510e+05],
        [5.3337e+02, 4.9175e+02, 5.0795e+02, 4.8180e+02],
        [4.4916e+05, 4.1404e+05, 4.2770e+05, 4.0570e+05],
        [5.6066e+05, 5.1682e+05, 5.3387e+05, 5.0641e+05],
        [5.3337e+02, 4.9175e+02, 5.0795e+02, 4.8180e+02],
        [6.0752e+05, 5.6001e+05, 5.7849e+05, 5.4874e+05],
        [4.4639e+05, 4.1148e+05, 4.2506e+05, 4.0320e+05],
        [4.3581e+05, 4.0173e+05, 4.1499e+05, 3.9364e+05],
        [4.3641e+05, 4.0229e+05, 4.1556e+05, 3.9419e+05],
        [4.8216e+05, 4.4445e+05, 4.5912e+05, 4.3550e+05],
        [4.7110e+05, 4.3427e+05, 4.4859e+05, 4.2552e+05],
        [6.1363e+05, 5.6565e+05, 5.8431e+05, 5.5426e+05],
        [4.317

tensor([[6.5653e+05, 6.1046e+05, 6.2920e+05, 5.9729e+05],
        [7.3792e+02, 6.8624e+02, 7.0728e+02, 6.7137e+02],
        [7.0634e+05, 6.5677e+05, 6.7693e+05, 6.4260e+05],
        [6.1423e+05, 5.7113e+05, 5.8866e+05, 5.5880e+05],
        [7.0218e+05, 6.5291e+05, 6.7295e+05, 6.3882e+05],
        [6.6251e+05, 6.1602e+05, 6.3493e+05, 6.0272e+05],
        [6.1608e+05, 5.7285e+05, 5.9043e+05, 5.6048e+05],
        [6.4168e+05, 5.9665e+05, 6.1497e+05, 5.8377e+05],
        [6.6725e+05, 6.2043e+05, 6.3948e+05, 6.0704e+05],
        [7.1303e+05, 6.6300e+05, 6.8335e+05, 6.4869e+05],
        [7.3792e+02, 6.8624e+02, 7.0728e+02, 6.7137e+02],
        [6.6734e+05, 6.2051e+05, 6.3956e+05, 6.0712e+05],
        [6.6607e+05, 6.1933e+05, 6.3834e+05, 6.0597e+05],
        [6.7002e+05, 6.2300e+05, 6.4213e+05, 6.0956e+05],
        [7.3792e+02, 6.8624e+02, 7.0728e+02, 6.7137e+02],
        [6.6097e+05, 6.1458e+05, 6.3345e+05, 6.0132e+05],
        [6.0206e+05, 5.5982e+05, 5.7700e+05, 5.4773e+05],
        [7.379

tensor([[9.3382e+05, 8.7459e+05, 8.9855e+05, 8.5407e+05],
        [8.8550e+05, 8.2933e+05, 8.5206e+05, 8.0988e+05],
        [1.0060e+03, 9.4233e+02, 9.6813e+02, 9.2017e+02],
        [9.4135e+05, 8.8164e+05, 9.0580e+05, 8.6096e+05],
        [9.4733e+05, 8.8724e+05, 9.1156e+05, 8.6643e+05],
        [1.1660e+06, 1.0920e+06, 1.1219e+06, 1.0664e+06],
        [9.9264e+05, 9.2967e+05, 9.5515e+05, 9.0786e+05],
        [1.0060e+03, 9.4233e+02, 9.6813e+02, 9.2017e+02],
        [9.9115e+05, 9.2828e+05, 9.5372e+05, 9.0650e+05],
        [8.5136e+05, 7.9736e+05, 8.1921e+05, 7.7865e+05],
        [1.0060e+03, 9.4233e+02, 9.6813e+02, 9.2017e+02],
        [9.1699e+05, 8.5883e+05, 8.8236e+05, 8.3868e+05],
        [8.8460e+05, 8.2849e+05, 8.5120e+05, 8.0905e+05],
        [8.9093e+05, 8.3442e+05, 8.5729e+05, 8.1484e+05],
        [9.0766e+05, 8.5009e+05, 8.7338e+05, 8.3014e+05],
        [1.0060e+03, 9.4233e+02, 9.6813e+02, 9.2017e+02],
        [1.0060e+03, 9.4233e+02, 9.6813e+02, 9.2017e+02],
        [9.552

tensor([[1.3531e+03, 1.2753e+03, 1.3055e+03, 1.2443e+03],
        [1.3531e+03, 1.2753e+03, 1.3055e+03, 1.2443e+03],
        [1.3196e+06, 1.2437e+06, 1.2731e+06, 1.2134e+06],
        [1.2934e+06, 1.2189e+06, 1.2478e+06, 1.1893e+06],
        [1.3084e+06, 1.2331e+06, 1.2623e+06, 1.2031e+06],
        [1.3531e+03, 1.2753e+03, 1.3055e+03, 1.2443e+03],
        [1.1208e+06, 1.0563e+06, 1.0813e+06, 1.0306e+06],
        [1.1097e+06, 1.0458e+06, 1.0706e+06, 1.0204e+06],
        [1.3531e+03, 1.2753e+03, 1.3055e+03, 1.2443e+03],
        [1.2200e+06, 1.1498e+06, 1.1770e+06, 1.1218e+06],
        [1.3531e+03, 1.2753e+03, 1.3055e+03, 1.2443e+03],
        [1.2264e+06, 1.1558e+06, 1.1832e+06, 1.1277e+06],
        [1.3531e+03, 1.2753e+03, 1.3055e+03, 1.2443e+03],
        [1.2254e+06, 1.1549e+06, 1.1822e+06, 1.1268e+06],
        [1.1222e+06, 1.0577e+06, 1.0827e+06, 1.0320e+06],
        [1.2759e+06, 1.2025e+06, 1.2309e+06, 1.1732e+06],
        [1.1967e+06, 1.1278e+06, 1.1545e+06, 1.1004e+06],
        [1.198

tensor([[1.6978e+06, 1.6064e+06, 1.6425e+06, 1.5672e+06],
        [1.4998e+06, 1.4191e+06, 1.4510e+06, 1.3844e+06],
        [1.5505e+06, 1.4670e+06, 1.5000e+06, 1.4312e+06],
        [1.7964e+03, 1.6997e+03, 1.7379e+03, 1.6582e+03],
        [1.7260e+06, 1.6330e+06, 1.6697e+06, 1.5932e+06],
        [1.5073e+06, 1.4261e+06, 1.4582e+06, 1.3913e+06],
        [1.5418e+06, 1.4587e+06, 1.4915e+06, 1.4232e+06],
        [1.6284e+06, 1.5407e+06, 1.5753e+06, 1.5031e+06],
        [1.6280e+06, 1.5403e+06, 1.5749e+06, 1.5027e+06],
        [1.5153e+06, 1.4336e+06, 1.4659e+06, 1.3987e+06],
        [1.4766e+06, 1.3971e+06, 1.4285e+06, 1.3630e+06],
        [1.5761e+06, 1.4912e+06, 1.5247e+06, 1.4548e+06],
        [1.6051e+06, 1.5187e+06, 1.5528e+06, 1.4816e+06],
        [1.7101e+06, 1.6180e+06, 1.6544e+06, 1.5785e+06],
        [1.4557e+06, 1.3773e+06, 1.4082e+06, 1.3437e+06],
        [1.6528e+06, 1.5638e+06, 1.5989e+06, 1.5256e+06],
        [1.6730e+06, 1.5829e+06, 1.6184e+06, 1.5443e+06],
        [1.706

tensor([[2.3526e+03, 2.2378e+03, 2.2854e+03, 2.1814e+03],
        [2.1461e+06, 2.0413e+06, 2.0848e+06, 1.9900e+06],
        [2.0918e+06, 1.9896e+06, 2.0320e+06, 1.9396e+06],
        [2.0857e+06, 1.9838e+06, 2.0261e+06, 1.9339e+06],
        [1.9652e+06, 1.8692e+06, 1.9090e+06, 1.8222e+06],
        [2.2271e+06, 2.1184e+06, 2.1635e+06, 2.0651e+06],
        [2.3526e+03, 2.2378e+03, 2.2854e+03, 2.1814e+03],
        [2.1116e+06, 2.0085e+06, 2.0513e+06, 1.9579e+06],
        [2.6540e+06, 2.5244e+06, 2.5782e+06, 2.4609e+06],
        [2.2703e+06, 2.1594e+06, 2.2054e+06, 2.1051e+06],
        [2.0660e+06, 1.9651e+06, 2.0069e+06, 1.9156e+06],
        [2.3526e+03, 2.2378e+03, 2.2854e+03, 2.1814e+03],
        [2.3526e+03, 2.2378e+03, 2.2854e+03, 2.1814e+03],
        [2.3526e+03, 2.2378e+03, 2.2854e+03, 2.1814e+03],
        [2.2343e+06, 2.1251e+06, 2.1704e+06, 2.0717e+06],
        [1.9917e+06, 1.8944e+06, 1.9348e+06, 1.8467e+06],
        [1.9480e+06, 1.8528e+06, 1.8923e+06, 1.8062e+06],
        [2.352

tensor([[2.6574e+06, 2.5383e+06, 2.5900e+06, 2.4748e+06],
        [2.7605e+06, 2.6367e+06, 2.6905e+06, 2.5708e+06],
        [3.0503e+03, 2.9137e+03, 2.9730e+03, 2.8408e+03],
        [2.9602e+06, 2.8276e+06, 2.8852e+06, 2.7569e+06],
        [3.0503e+03, 2.9137e+03, 2.9730e+03, 2.8408e+03],
        [2.9766e+06, 2.8432e+06, 2.9011e+06, 2.7722e+06],
        [2.8050e+06, 2.6793e+06, 2.7339e+06, 2.6123e+06],
        [2.7966e+06, 2.6713e+06, 2.7257e+06, 2.6045e+06],
        [2.7510e+06, 2.6277e+06, 2.6812e+06, 2.5620e+06],
        [2.8931e+06, 2.7634e+06, 2.8197e+06, 2.6943e+06],
        [2.7689e+06, 2.6448e+06, 2.6987e+06, 2.5787e+06],
        [3.5019e+06, 3.3450e+06, 3.4131e+06, 3.2613e+06],
        [2.8244e+06, 2.6978e+06, 2.7528e+06, 2.6304e+06],
        [3.3967e+06, 3.2445e+06, 3.3106e+06, 3.1634e+06],
        [3.1000e+06, 2.9611e+06, 3.0214e+06, 2.8871e+06],
        [2.7790e+06, 2.6544e+06, 2.7085e+06, 2.5881e+06],
        [2.8467e+06, 2.7191e+06, 2.7745e+06, 2.6512e+06],
        [3.047

tensor([[3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [3.5994e+06, 3.4519e+06, 3.5177e+06, 3.3668e+06],
        [3.8349e+06, 3.6778e+06, 3.7479e+06, 3.5872e+06],
        [3.6350e+06, 3.4861e+06, 3.5525e+06, 3.4002e+06],
        [3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [4.1999e+06, 4.0279e+06, 4.1046e+06, 3.9286e+06],
        [3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [3.2576e+06, 3.1241e+06, 3.1836e+06, 3.0471e+06],
        [3.4471e+06, 3.3059e+06, 3.3689e+06, 3.2244e+06],
        [3.9143e+03, 3.7540e+03, 3.8255e+03, 3.6614e+03],
        [3.9806e+06, 3.8175e+06, 3.8903e+06, 3.7234e+06],
        [3.2841e+06, 3.1496e+06, 3.2096e+06, 3.0719e+06],
        [3.3181e+06, 3.1822e+06, 3.2428e+06, 3.1037e+06],
        [3.7303e+06, 3.5775e+06, 3.6456e+06, 3.4893e+06],
        [3.914

tensor([[4.4840e+06, 4.3142e+06, 4.3907e+06, 4.2111e+06],
        [4.5656e+06, 4.3928e+06, 4.4706e+06, 4.2878e+06],
        [4.7348e+06, 4.5555e+06, 4.6363e+06, 4.4466e+06],
        [4.1544e+06, 3.9971e+06, 4.0680e+06, 3.9016e+06],
        [4.4776e+06, 4.3081e+06, 4.3845e+06, 4.2051e+06],
        [4.6159e+06, 4.4411e+06, 4.5199e+06, 4.3350e+06],
        [4.2692e+06, 4.1076e+06, 4.1804e+06, 4.0094e+06],
        [4.9575e+06, 4.7698e+06, 4.8544e+06, 4.6558e+06],
        [4.0840e+06, 3.9294e+06, 3.9991e+06, 3.8355e+06],
        [4.4733e+06, 4.3040e+06, 4.3803e+06, 4.2011e+06],
        [4.6850e+06, 4.5076e+06, 4.5875e+06, 4.3999e+06],
        [4.6630e+06, 4.4865e+06, 4.5660e+06, 4.3793e+06],
        [4.9775e+03, 4.7892e+03, 4.8741e+03, 4.6747e+03],
        [4.8300e+06, 4.6472e+06, 4.7296e+06, 4.5361e+06],
        [4.9775e+03, 4.7892e+03, 4.8741e+03, 4.6747e+03],
        [4.4839e+06, 4.3141e+06, 4.3906e+06, 4.2110e+06],
        [4.6496e+06, 4.4736e+06, 4.5529e+06, 4.3666e+06],
        [4.929

tensor([[6.5060e+06, 6.2770e+06, 6.3824e+06, 6.1335e+06],
        [6.2756e+03, 6.0548e+03, 6.1565e+03, 5.9163e+03],
        [5.6454e+06, 5.4467e+06, 5.5382e+06, 5.3221e+06],
        [5.3510e+06, 5.1626e+06, 5.2493e+06, 5.0446e+06],
        [6.2756e+03, 6.0548e+03, 6.1565e+03, 5.9163e+03],
        [6.2756e+03, 6.0548e+03, 6.1565e+03, 5.9163e+03],
        [6.0231e+06, 5.8111e+06, 5.9087e+06, 5.6782e+06],
        [5.5837e+06, 5.3872e+06, 5.4777e+06, 5.2640e+06],
        [6.0457e+06, 5.8329e+06, 5.9309e+06, 5.6995e+06],
        [6.2756e+03, 6.0548e+03, 6.1565e+03, 5.9163e+03],
        [5.9221e+06, 5.7136e+06, 5.8096e+06, 5.5830e+06],
        [6.5445e+06, 6.3141e+06, 6.4202e+06, 6.1698e+06],
        [6.2756e+03, 6.0548e+03, 6.1565e+03, 5.9163e+03],
        [5.6946e+06, 5.4942e+06, 5.5865e+06, 5.3686e+06],
        [5.5638e+06, 5.3680e+06, 5.4582e+06, 5.2452e+06],
        [5.9801e+06, 5.7696e+06, 5.8665e+06, 5.6377e+06],
        [5.7947e+06, 5.5907e+06, 5.6847e+06, 5.4629e+06],
        [6.275

tensor([[7.2326e+06, 6.9867e+06, 7.1043e+06, 6.8362e+06],
        [7.7954e+06, 7.5303e+06, 7.6571e+06, 7.3682e+06],
        [6.7123e+06, 6.4841e+06, 6.5932e+06, 6.3444e+06],
        [7.7870e+06, 7.5223e+06, 7.6489e+06, 7.3603e+06],
        [7.2024e+06, 6.9575e+06, 7.0746e+06, 6.8077e+06],
        [7.3037e+06, 7.0554e+06, 7.1742e+06, 6.9035e+06],
        [7.1255e+06, 6.8833e+06, 6.9991e+06, 6.7351e+06],
        [6.5786e+06, 6.3550e+06, 6.4619e+06, 6.2181e+06],
        [7.3924e+06, 7.1411e+06, 7.2612e+06, 6.9873e+06],
        [7.4425e+06, 7.1895e+06, 7.3105e+06, 7.0347e+06],
        [6.9517e+06, 6.7153e+06, 6.8283e+06, 6.5707e+06],
        [8.0594e+06, 7.7854e+06, 7.9165e+06, 7.6178e+06],
        [7.7154e+06, 7.4531e+06, 7.5785e+06, 7.2925e+06],
        [7.1636e+06, 6.9201e+06, 7.0365e+06, 6.7710e+06],
        [7.2824e+06, 7.0348e+06, 7.1532e+06, 6.8833e+06],
        [7.8488e+03, 7.5821e+03, 7.7097e+03, 7.4187e+03],
        [6.7863e+06, 6.5556e+06, 6.6659e+06, 6.4144e+06],
        [7.731

tensor([[8.3269e+06, 8.0557e+06, 8.1886e+06, 7.8878e+06],
        [8.2797e+06, 8.0100e+06, 8.1421e+06, 7.8430e+06],
        [9.1354e+06, 8.8379e+06, 8.9837e+06, 8.6536e+06],
        [9.5861e+06, 9.2738e+06, 9.4268e+06, 9.0805e+06],
        [9.7378e+03, 9.4207e+03, 9.5761e+03, 9.2243e+03],
        [9.0881e+06, 8.7921e+06, 8.9371e+06, 8.6088e+06],
        [9.7378e+03, 9.4207e+03, 9.5761e+03, 9.2243e+03],
        [1.0387e+07, 1.0049e+07, 1.0215e+07, 9.8396e+06],
        [9.7378e+03, 9.4207e+03, 9.5761e+03, 9.2243e+03],
        [8.2258e+06, 7.9579e+06, 8.0892e+06, 7.7920e+06],
        [8.6279e+06, 8.3468e+06, 8.4845e+06, 8.1728e+06],
        [9.4474e+06, 9.1396e+06, 9.2904e+06, 8.9491e+06],
        [8.7876e+06, 8.5013e+06, 8.6416e+06, 8.3241e+06],
        [8.7244e+06, 8.4402e+06, 8.5795e+06, 8.2643e+06],
        [8.9548e+06, 8.6631e+06, 8.8060e+06, 8.4825e+06],
        [8.3586e+06, 8.0863e+06, 8.2197e+06, 7.9177e+06],
        [9.0417e+06, 8.7472e+06, 8.8915e+06, 8.5648e+06],
        [8.837

tensor([[1.1657e+07, 1.1290e+07, 1.1480e+07, 1.1072e+07],
        [1.1983e+04, 1.1605e+04, 1.1801e+04, 1.1382e+04],
        [1.1440e+07, 1.1079e+07, 1.1265e+07, 1.0865e+07],
        [1.1983e+04, 1.1605e+04, 1.1801e+04, 1.1382e+04],
        [1.4886e+07, 1.4416e+07, 1.4659e+07, 1.4138e+07],
        [1.1983e+04, 1.1605e+04, 1.1801e+04, 1.1382e+04],
        [1.1983e+04, 1.1605e+04, 1.1801e+04, 1.1382e+04],
        [1.1983e+04, 1.1605e+04, 1.1801e+04, 1.1382e+04],
        [1.1117e+07, 1.0766e+07, 1.0948e+07, 1.0559e+07],
        [1.1771e+07, 1.1399e+07, 1.1591e+07, 1.1180e+07],
        [1.0414e+07, 1.0085e+07, 1.0255e+07, 9.8908e+06],
        [1.0354e+07, 1.0028e+07, 1.0197e+07, 9.8343e+06],
        [1.1009e+07, 1.0662e+07, 1.0842e+07, 1.0457e+07],
        [1.0692e+07, 1.0355e+07, 1.0529e+07, 1.0155e+07],
        [1.1326e+07, 1.0968e+07, 1.1153e+07, 1.0757e+07],
        [1.1180e+07, 1.0827e+07, 1.1010e+07, 1.0618e+07],
        [1.1123e+07, 1.0772e+07, 1.0953e+07, 1.0564e+07],
        [1.162

tensor([[1.2568e+07, 1.2178e+07, 1.2390e+07, 1.1970e+07],
        [1.2493e+07, 1.2105e+07, 1.2316e+07, 1.1898e+07],
        [1.3959e+07, 1.3526e+07, 1.3761e+07, 1.3294e+07],
        [1.2441e+07, 1.2056e+07, 1.2266e+07, 1.1849e+07],
        [1.4168e+07, 1.3729e+07, 1.3968e+07, 1.3494e+07],
        [1.3135e+07, 1.2727e+07, 1.2949e+07, 1.2509e+07],
        [1.4487e+07, 1.4038e+07, 1.4282e+07, 1.3797e+07],
        [1.5265e+07, 1.4792e+07, 1.5050e+07, 1.4539e+07],
        [1.3674e+07, 1.3250e+07, 1.3480e+07, 1.3023e+07],
        [1.7444e+07, 1.6903e+07, 1.7197e+07, 1.6614e+07],
        [1.5027e+07, 1.4561e+07, 1.4815e+07, 1.4312e+07],
        [1.3479e+07, 1.3061e+07, 1.3289e+07, 1.2838e+07],
        [1.2398e+07, 1.2013e+07, 1.2222e+07, 1.1808e+07],
        [1.2781e+07, 1.2384e+07, 1.2600e+07, 1.2172e+07],
        [1.4646e+04, 1.4192e+04, 1.4439e+04, 1.3949e+04],
        [1.4646e+04, 1.4192e+04, 1.4439e+04, 1.3949e+04],
        [1.4646e+04, 1.4192e+04, 1.4439e+04, 1.3949e+04],
        [1.252

tensor([[1.5197e+07, 1.4733e+07, 1.4997e+07, 1.4503e+07],
        [1.6585e+07, 1.6079e+07, 1.6366e+07, 1.5827e+07],
        [1.8412e+07, 1.7849e+07, 1.8169e+07, 1.7570e+07],
        [1.6831e+07, 1.6317e+07, 1.6609e+07, 1.6062e+07],
        [1.5736e+07, 1.5256e+07, 1.5529e+07, 1.5017e+07],
        [1.5815e+07, 1.5332e+07, 1.5606e+07, 1.5092e+07],
        [1.5816e+07, 1.5334e+07, 1.5608e+07, 1.5094e+07],
        [1.6737e+07, 1.6226e+07, 1.6516e+07, 1.5972e+07],
        [1.6123e+07, 1.5631e+07, 1.5911e+07, 1.5387e+07],
        [1.8091e+07, 1.7539e+07, 1.7852e+07, 1.7264e+07],
        [1.6066e+07, 1.5576e+07, 1.5854e+07, 1.5332e+07],
        [1.7787e+04, 1.7244e+04, 1.7552e+04, 1.6974e+04],
        [1.6786e+07, 1.6274e+07, 1.6565e+07, 1.6019e+07],
        [1.7787e+04, 1.7244e+04, 1.7552e+04, 1.6974e+04],
        [1.7609e+07, 1.7072e+07, 1.7377e+07, 1.6805e+07],
        [1.5098e+07, 1.4637e+07, 1.4899e+07, 1.4408e+07],
        [1.5559e+07, 1.5084e+07, 1.5354e+07, 1.4849e+07],
        [1.579

tensor([[1.7869e+07, 1.7336e+07, 1.7648e+07, 1.7085e+07],
        [2.1678e+07, 2.1032e+07, 2.1409e+07, 2.0726e+07],
        [2.1473e+04, 2.0833e+04, 2.1206e+04, 2.0530e+04],
        [1.8868e+07, 1.8305e+07, 1.8634e+07, 1.8039e+07],
        [1.9746e+07, 1.9157e+07, 1.9501e+07, 1.8879e+07],
        [2.1473e+04, 2.0833e+04, 2.1206e+04, 2.0530e+04],
        [2.1473e+04, 2.0833e+04, 2.1206e+04, 2.0530e+04],
        [2.0454e+07, 1.9844e+07, 2.0200e+07, 1.9556e+07],
        [2.0459e+07, 1.9849e+07, 2.0205e+07, 1.9561e+07],
        [2.0306e+07, 1.9700e+07, 2.0054e+07, 1.9414e+07],
        [1.8722e+07, 1.8164e+07, 1.8489e+07, 1.7900e+07],
        [2.0468e+07, 1.9857e+07, 2.0213e+07, 1.9569e+07],
        [2.0413e+07, 1.9805e+07, 2.0160e+07, 1.9517e+07],
        [2.2359e+07, 2.1692e+07, 2.2081e+07, 2.1377e+07],
        [2.0187e+07, 1.9585e+07, 1.9936e+07, 1.9300e+07],
        [2.3207e+07, 2.2515e+07, 2.2919e+07, 2.2188e+07],
        [2.1473e+04, 2.0833e+04, 2.1206e+04, 2.0530e+04],
        [1.957

tensor([[2.5773e+04, 2.5030e+04, 2.5439e+04, 2.4676e+04],
        [2.3596e+07, 2.2915e+07, 2.3290e+07, 2.2592e+07],
        [2.5773e+04, 2.5030e+04, 2.5439e+04, 2.4676e+04],
        [2.5039e+07, 2.4317e+07, 2.4714e+07, 2.3974e+07],
        [2.4037e+07, 2.3344e+07, 2.3726e+07, 2.3015e+07],
        [2.3700e+07, 2.3016e+07, 2.3392e+07, 2.2691e+07],
        [2.3183e+07, 2.2514e+07, 2.2882e+07, 2.2197e+07],
        [2.2510e+07, 2.1861e+07, 2.2218e+07, 2.1553e+07],
        [2.3848e+07, 2.3160e+07, 2.3538e+07, 2.2833e+07],
        [2.4997e+07, 2.4276e+07, 2.4672e+07, 2.3933e+07],
        [2.1426e+07, 2.0808e+07, 2.1148e+07, 2.0514e+07],
        [2.3960e+07, 2.3268e+07, 2.3649e+07, 2.2940e+07],
        [2.2077e+07, 2.1440e+07, 2.1791e+07, 2.1138e+07],
        [2.2057e+07, 2.1420e+07, 2.1771e+07, 2.1118e+07],
        [2.5187e+07, 2.4460e+07, 2.4860e+07, 2.4115e+07],
        [2.6307e+07, 2.5548e+07, 2.5966e+07, 2.5188e+07],
        [2.5773e+04, 2.5030e+04, 2.5439e+04, 2.4676e+04],
        [2.360

tensor([[2.5716e+07, 2.5001e+07, 2.5389e+07, 2.4660e+07],
        [2.6092e+07, 2.5366e+07, 2.5761e+07, 2.5021e+07],
        [2.9180e+07, 2.8368e+07, 2.8809e+07, 2.7982e+07],
        [2.9501e+07, 2.8680e+07, 2.9126e+07, 2.8289e+07],
        [2.8582e+07, 2.7787e+07, 2.8219e+07, 2.7408e+07],
        [3.0728e+04, 2.9873e+04, 3.0338e+04, 2.9467e+04],
        [2.6677e+07, 2.5935e+07, 2.6338e+07, 2.5582e+07],
        [2.6451e+07, 2.5715e+07, 2.6115e+07, 2.5365e+07],
        [2.7546e+07, 2.6779e+07, 2.7196e+07, 2.6415e+07],
        [2.5377e+07, 2.4671e+07, 2.5054e+07, 2.4335e+07],
        [2.6259e+07, 2.5528e+07, 2.5925e+07, 2.5180e+07],
        [2.9162e+07, 2.8351e+07, 2.8792e+07, 2.7965e+07],
        [2.5528e+07, 2.4818e+07, 2.5204e+07, 2.4480e+07],
        [2.9897e+07, 2.9065e+07, 2.9517e+07, 2.8669e+07],
        [2.8340e+07, 2.7551e+07, 2.7980e+07, 2.7176e+07],
        [2.6077e+07, 2.5352e+07, 2.5746e+07, 2.5007e+07],
        [3.0728e+04, 2.9873e+04, 3.0338e+04, 2.9467e+04],
        [3.072

tensor([[3.6445e+04, 3.5458e+04, 3.5985e+04, 3.5015e+04],
        [3.8297e+07, 3.7260e+07, 3.7814e+07, 3.6795e+07],
        [3.4187e+07, 3.3261e+07, 3.3755e+07, 3.2846e+07],
        [3.5041e+07, 3.4092e+07, 3.4598e+07, 3.3666e+07],
        [3.6445e+04, 3.5458e+04, 3.5985e+04, 3.5015e+04],
        [3.2105e+07, 3.1235e+07, 3.1699e+07, 3.0845e+07],
        [3.3575e+07, 3.2665e+07, 3.3151e+07, 3.2258e+07],
        [3.7846e+07, 3.6821e+07, 3.7368e+07, 3.6362e+07],
        [3.6445e+04, 3.5458e+04, 3.5985e+04, 3.5015e+04],
        [3.5778e+07, 3.4809e+07, 3.5326e+07, 3.4374e+07],
        [3.0736e+07, 2.9903e+07, 3.0348e+07, 2.9530e+07],
        [3.3904e+07, 3.2985e+07, 3.3476e+07, 3.2574e+07],
        [3.3910e+07, 3.2991e+07, 3.3481e+07, 3.2579e+07],
        [3.3667e+07, 3.2755e+07, 3.3242e+07, 3.2346e+07],
        [3.3222e+07, 3.2322e+07, 3.2803e+07, 3.1919e+07],
        [3.6445e+04, 3.5458e+04, 3.5985e+04, 3.5015e+04],
        [3.2928e+07, 3.2036e+07, 3.2512e+07, 3.1636e+07],
        [3.644

tensor([[4.3144e+07, 4.2013e+07, 4.2621e+07, 4.1520e+07],
        [3.6517e+07, 3.5559e+07, 3.6074e+07, 3.5143e+07],
        [4.0142e+07, 3.9090e+07, 3.9656e+07, 3.8632e+07],
        [4.2958e+04, 4.1832e+04, 4.2438e+04, 4.1342e+04],
        [4.5825e+07, 4.4624e+07, 4.5270e+07, 4.4101e+07],
        [4.2765e+07, 4.1643e+07, 4.2246e+07, 4.1155e+07],
        [3.9138e+07, 3.8112e+07, 3.8664e+07, 3.7665e+07],
        [3.8109e+07, 3.7109e+07, 3.7647e+07, 3.6674e+07],
        [4.2958e+04, 4.1832e+04, 4.2438e+04, 4.1342e+04],
        [4.2958e+04, 4.1832e+04, 4.2438e+04, 4.1342e+04],
        [3.7474e+07, 3.6491e+07, 3.7020e+07, 3.6064e+07],
        [4.2958e+04, 4.1832e+04, 4.2438e+04, 4.1342e+04],
        [3.9986e+07, 3.8937e+07, 3.9501e+07, 3.8481e+07],
        [3.6630e+07, 3.5669e+07, 3.6185e+07, 3.5251e+07],
        [3.8101e+07, 3.7102e+07, 3.7639e+07, 3.6667e+07],
        [4.3529e+07, 4.2387e+07, 4.3001e+07, 4.1890e+07],
        [4.2958e+04, 4.1832e+04, 4.2438e+04, 4.1342e+04],
        [4.295

tensor([[5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [4.7006e+07, 4.5810e+07, 4.6459e+07, 4.5303e+07],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [4.8099e+07, 4.6875e+07, 4.7540e+07, 4.6357e+07],
        [4.6237e+07, 4.5060e+07, 4.5699e+07, 4.4561e+07],
        [5.1618e+07, 5.0304e+07, 5.1017e+07, 4.9747e+07],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [5.0436e+04, 4.9152e+04, 4.9849e+04, 4.8608e+04],
        [6.1786e+07, 6.0213e+07, 6.1067e+07, 5.9547e+07],
        [4.9514e+07, 4.8254e+07, 4.8938e+07, 4.7720e+07],
        [4.6118e+07, 4.4944e+07, 4.5581e+07, 4.4447e+07],
        [4.2434e+07, 4.1354e+07, 4.1940e+07, 4.0896e+07],
        [4.4916e+07, 4.3773e+07, 4.4393e+07, 4.3289e+07],
        [4.302

tensor([[5.4625e+07, 5.3278e+07, 5.4021e+07, 5.2704e+07],
        [5.4713e+07, 5.3364e+07, 5.4108e+07, 5.2789e+07],
        [5.2558e+07, 5.1262e+07, 5.1977e+07, 5.0710e+07],
        [5.5359e+07, 5.3993e+07, 5.4747e+07, 5.3412e+07],
        [5.8990e+04, 5.7536e+04, 5.8338e+04, 5.6916e+04],
        [5.3989e+07, 5.2657e+07, 5.3392e+07, 5.2090e+07],
        [5.4303e+07, 5.2964e+07, 5.3703e+07, 5.2394e+07],
        [5.6096e+07, 5.4712e+07, 5.5476e+07, 5.4123e+07],
        [6.6575e+07, 6.4933e+07, 6.5839e+07, 6.4234e+07],
        [5.4619e+07, 5.3272e+07, 5.4015e+07, 5.2699e+07],
        [5.8990e+04, 5.7536e+04, 5.8338e+04, 5.6916e+04],
        [5.5731e+07, 5.4357e+07, 5.5115e+07, 5.3771e+07],
        [5.8811e+07, 5.7361e+07, 5.8161e+07, 5.6743e+07],
        [6.4367e+07, 6.2779e+07, 6.3655e+07, 6.2103e+07],
        [5.1891e+07, 5.0611e+07, 5.1317e+07, 5.0066e+07],
        [5.7565e+07, 5.6145e+07, 5.6928e+07, 5.5540e+07],
        [5.6472e+07, 5.5079e+07, 5.5848e+07, 5.4486e+07],
        [5.899

tensor([[6.2603e+07, 6.1110e+07, 6.1922e+07, 6.0467e+07],
        [6.1310e+07, 5.9848e+07, 6.0643e+07, 5.9218e+07],
        [6.6303e+07, 6.4722e+07, 6.5582e+07, 6.4040e+07],
        [7.9373e+07, 7.7480e+07, 7.8510e+07, 7.6664e+07],
        [5.8497e+07, 5.7102e+07, 5.7861e+07, 5.6501e+07],
        [7.6423e+07, 7.4600e+07, 7.5592e+07, 7.3815e+07],
        [6.8742e+04, 6.7103e+04, 6.7994e+04, 6.6396e+04],
        [5.9332e+07, 5.7917e+07, 5.8686e+07, 5.7307e+07],
        [7.1173e+07, 6.9476e+07, 7.0399e+07, 6.8744e+07],
        [6.5671e+07, 6.4105e+07, 6.4957e+07, 6.3430e+07],
        [6.3476e+07, 6.1962e+07, 6.2785e+07, 6.1309e+07],
        [5.8987e+07, 5.7580e+07, 5.8345e+07, 5.6973e+07],
        [6.1543e+07, 6.0075e+07, 6.0874e+07, 5.9443e+07],
        [7.0494e+07, 6.8813e+07, 6.9727e+07, 6.8088e+07],
        [6.6177e+07, 6.4599e+07, 6.5457e+07, 6.3918e+07],
        [6.8742e+04, 6.7103e+04, 6.7994e+04, 6.6396e+04],
        [6.7669e+07, 6.6056e+07, 6.6933e+07, 6.5360e+07],
        [6.874

tensor([[8.0477e+07, 7.8593e+07, 7.9627e+07, 7.7842e+07],
        [6.7589e+07, 6.6007e+07, 6.6876e+07, 6.5376e+07],
        [7.6688e+07, 7.4893e+07, 7.5878e+07, 7.4177e+07],
        [7.5016e+07, 7.3260e+07, 7.4224e+07, 7.2559e+07],
        [8.1051e+07, 7.9154e+07, 8.0195e+07, 7.8397e+07],
        [7.9767e+04, 7.7900e+04, 7.8925e+04, 7.7155e+04],
        [7.1125e+07, 6.9460e+07, 7.0374e+07, 6.8796e+07],
        [8.6785e+07, 8.4754e+07, 8.5869e+07, 8.3943e+07],
        [7.9767e+04, 7.7900e+04, 7.8925e+04, 7.7155e+04],
        [7.9767e+04, 7.7900e+04, 7.8925e+04, 7.7155e+04],
        [8.8722e+07, 8.6645e+07, 8.7785e+07, 8.5816e+07],
        [7.9767e+04, 7.7900e+04, 7.8925e+04, 7.7155e+04],
        [7.4272e+07, 7.2533e+07, 7.3487e+07, 7.1840e+07],
        [6.6287e+07, 6.4736e+07, 6.5587e+07, 6.4117e+07],
        [7.6060e+07, 7.4280e+07, 7.5257e+07, 7.3570e+07],
        [7.3443e+07, 7.1723e+07, 7.2667e+07, 7.1038e+07],
        [7.3741e+07, 7.2014e+07, 7.2962e+07, 7.1326e+07],
        [7.093

tensor([[9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [8.9414e+07, 8.7375e+07, 8.8477e+07, 8.6606e+07],
        [9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [7.9590e+07, 7.7776e+07, 7.8757e+07, 7.7091e+07],
        [9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [8.7292e+07, 8.5302e+07, 8.6378e+07, 8.4551e+07],
        [8.1578e+07, 7.9718e+07, 8.0723e+07, 7.9016e+07],
        [8.6766e+07, 8.4788e+07, 8.5857e+07, 8.4042e+07],
        [8.4310e+07, 8.2388e+07, 8.3427e+07, 8.1663e+07],
        [7.9869e+07, 7.8049e+07, 7.9033e+07, 7.7362e+07],
        [7.9041e+07, 7.7240e+07, 7.8214e+07, 7.6560e+07],
        [8.2633e+07, 8.0750e+07, 8.1768e+07, 8.0039e+07],
        [8.5552e+07, 8.3602e+07, 8.4656e+07, 8.2866e+07],
        [9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [9.2191e+04, 9.0090e+04, 9.1226e+04, 8.9297e+04],
        [8.208

tensor([[1.0608e+05, 1.0381e+05, 1.0493e+05, 1.0288e+05],
        [1.0024e+08, 9.8091e+07, 9.9151e+07, 9.7213e+07],
        [9.1383e+07, 8.9428e+07, 9.0394e+07, 8.8628e+07],
        [9.4017e+07, 9.2005e+07, 9.2999e+07, 9.1182e+07],
        [9.0666e+07, 8.8726e+07, 8.9684e+07, 8.7932e+07],
        [9.3360e+07, 9.1362e+07, 9.2349e+07, 9.0545e+07],
        [8.8066e+07, 8.6182e+07, 8.7113e+07, 8.5410e+07],
        [9.8039e+07, 9.5941e+07, 9.6978e+07, 9.5082e+07],
        [1.0093e+08, 9.8767e+07, 9.9834e+07, 9.7883e+07],
        [8.7751e+07, 8.5873e+07, 8.6801e+07, 8.5105e+07],
        [9.7155e+07, 9.5076e+07, 9.6104e+07, 9.4225e+07],
        [9.0555e+07, 8.8617e+07, 8.9575e+07, 8.7824e+07],
        [9.7044e+07, 9.4967e+07, 9.5993e+07, 9.4117e+07],
        [1.0162e+08, 9.9446e+07, 1.0052e+08, 9.8556e+07],
        [9.9878e+07, 9.7740e+07, 9.8796e+07, 9.6866e+07],
        [1.1056e+08, 1.0819e+08, 1.0936e+08, 1.0722e+08],
        [1.0608e+05, 1.0381e+05, 1.0493e+05, 1.0288e+05],
        [1.042

tensor([[1.0765e+08, 1.0547e+08, 1.0643e+08, 1.0451e+08],
        [1.1664e+08, 1.1427e+08, 1.1531e+08, 1.1323e+08],
        [1.2168e+05, 1.1922e+05, 1.2030e+05, 1.1813e+05],
        [1.0569e+08, 1.0355e+08, 1.0449e+08, 1.0261e+08],
        [1.3350e+08, 1.3080e+08, 1.3198e+08, 1.2961e+08],
        [1.2168e+05, 1.1922e+05, 1.2030e+05, 1.1813e+05],
        [1.2168e+05, 1.1922e+05, 1.2030e+05, 1.1813e+05],
        [1.0927e+08, 1.0705e+08, 1.0802e+08, 1.0608e+08],
        [1.2168e+05, 1.1922e+05, 1.2030e+05, 1.1813e+05],
        [1.2168e+05, 1.1922e+05, 1.2030e+05, 1.1813e+05],
        [1.1161e+08, 1.0935e+08, 1.1035e+08, 1.0836e+08],
        [1.4519e+08, 1.4225e+08, 1.4354e+08, 1.4095e+08],
        [1.0576e+08, 1.0362e+08, 1.0456e+08, 1.0267e+08],
        [1.1281e+08, 1.1053e+08, 1.1153e+08, 1.0952e+08],
        [1.1309e+08, 1.1080e+08, 1.1180e+08, 1.0979e+08],
        [1.1651e+08, 1.1415e+08, 1.1519e+08, 1.1311e+08],
        [1.1591e+08, 1.1356e+08, 1.1459e+08, 1.1253e+08],
        [1.216

tensor([[1.4105e+08, 1.3832e+08, 1.3930e+08, 1.3707e+08],
        [1.5652e+08, 1.5349e+08, 1.5458e+08, 1.5210e+08],
        [1.3355e+08, 1.3096e+08, 1.3189e+08, 1.2977e+08],
        [1.3326e+08, 1.3068e+08, 1.3161e+08, 1.2950e+08],
        [1.2674e+08, 1.2428e+08, 1.2517e+08, 1.2316e+08],
        [1.2925e+08, 1.2675e+08, 1.2765e+08, 1.2560e+08],
        [1.3399e+08, 1.3140e+08, 1.3233e+08, 1.3021e+08],
        [1.4758e+08, 1.4472e+08, 1.4575e+08, 1.4341e+08],
        [1.2577e+08, 1.2334e+08, 1.2421e+08, 1.2222e+08],
        [1.2369e+08, 1.2130e+08, 1.2216e+08, 1.2020e+08],
        [1.3915e+05, 1.3645e+05, 1.3742e+05, 1.3522e+05],
        [1.2726e+08, 1.2479e+08, 1.2568e+08, 1.2366e+08],
        [1.5218e+08, 1.4923e+08, 1.5029e+08, 1.4788e+08],
        [1.3915e+05, 1.3645e+05, 1.3742e+05, 1.3522e+05],
        [1.4141e+08, 1.3867e+08, 1.3965e+08, 1.3741e+08],
        [1.3193e+08, 1.2937e+08, 1.3029e+08, 1.2820e+08],
        [1.2786e+08, 1.2538e+08, 1.2627e+08, 1.2425e+08],
        [1.377

tensor([[1.5867e+05, 1.5556e+05, 1.5655e+05, 1.5431e+05],
        [1.8699e+08, 1.8333e+08, 1.8450e+08, 1.8185e+08],
        [1.4618e+08, 1.4332e+08, 1.4423e+08, 1.4216e+08],
        [1.5514e+08, 1.5210e+08, 1.5307e+08, 1.5087e+08],
        [1.3652e+08, 1.3384e+08, 1.3470e+08, 1.3277e+08],
        [1.5249e+08, 1.4950e+08, 1.5045e+08, 1.4829e+08],
        [1.5536e+08, 1.5232e+08, 1.5329e+08, 1.5109e+08],
        [1.4731e+08, 1.4442e+08, 1.4534e+08, 1.4326e+08],
        [1.5867e+05, 1.5556e+05, 1.5655e+05, 1.5431e+05],
        [1.5867e+05, 1.5556e+05, 1.5655e+05, 1.5431e+05],
        [1.4275e+08, 1.3995e+08, 1.4084e+08, 1.3882e+08],
        [1.4753e+08, 1.4464e+08, 1.4557e+08, 1.4348e+08],
        [1.3908e+08, 1.3636e+08, 1.3722e+08, 1.3526e+08],
        [1.5079e+08, 1.4784e+08, 1.4878e+08, 1.4665e+08],
        [1.5867e+05, 1.5556e+05, 1.5655e+05, 1.5431e+05],
        [1.5653e+08, 1.5346e+08, 1.5444e+08, 1.5223e+08],
        [1.4290e+08, 1.4010e+08, 1.4099e+08, 1.3897e+08],
        [1.722

tensor([[1.8021e+05, 1.7667e+05, 1.7783e+05, 1.7536e+05],
        [1.5741e+08, 1.5432e+08, 1.5533e+08, 1.5317e+08],
        [1.5904e+08, 1.5592e+08, 1.5694e+08, 1.5476e+08],
        [1.8021e+05, 1.7667e+05, 1.7783e+05, 1.7536e+05],
        [1.7621e+08, 1.7276e+08, 1.7389e+08, 1.7147e+08],
        [1.6841e+08, 1.6510e+08, 1.6619e+08, 1.6387e+08],
        [1.8021e+05, 1.7667e+05, 1.7783e+05, 1.7536e+05],
        [1.8021e+05, 1.7667e+05, 1.7783e+05, 1.7536e+05],
        [1.6998e+08, 1.6665e+08, 1.6774e+08, 1.6541e+08],
        [1.6078e+08, 1.5762e+08, 1.5866e+08, 1.5645e+08],
        [1.7631e+08, 1.7285e+08, 1.7399e+08, 1.7157e+08],
        [1.5567e+08, 1.5261e+08, 1.5361e+08, 1.5148e+08],
        [1.6976e+08, 1.6642e+08, 1.6752e+08, 1.6519e+08],
        [1.9927e+08, 1.9536e+08, 1.9665e+08, 1.9391e+08],
        [1.8021e+05, 1.7667e+05, 1.7783e+05, 1.7536e+05],
        [1.6351e+08, 1.6031e+08, 1.6136e+08, 1.5912e+08],
        [1.5592e+08, 1.5286e+08, 1.5386e+08, 1.5172e+08],
        [1.659

tensor([[1.8387e+08, 1.8028e+08, 1.8144e+08, 1.7895e+08],
        [2.0410e+05, 2.0012e+05, 2.0141e+05, 1.9864e+05],
        [1.8970e+08, 1.8601e+08, 1.8720e+08, 1.8463e+08],
        [1.8944e+08, 1.8575e+08, 1.8695e+08, 1.8438e+08],
        [1.8547e+08, 1.8186e+08, 1.8303e+08, 1.8051e+08],
        [1.8709e+08, 1.8344e+08, 1.8463e+08, 1.8209e+08],
        [2.0410e+05, 2.0012e+05, 2.0141e+05, 1.9864e+05],
        [2.0410e+05, 2.0012e+05, 2.0141e+05, 1.9864e+05],
        [2.0410e+05, 2.0012e+05, 2.0141e+05, 1.9864e+05],
        [2.0422e+08, 2.0024e+08, 2.0153e+08, 1.9876e+08],
        [1.7923e+08, 1.7574e+08, 1.7687e+08, 1.7444e+08],
        [2.0490e+08, 2.0090e+08, 2.0220e+08, 1.9942e+08],
        [2.0410e+05, 2.0012e+05, 2.0141e+05, 1.9864e+05],
        [1.8911e+08, 1.8542e+08, 1.8662e+08, 1.8405e+08],
        [2.2697e+08, 2.2255e+08, 2.2398e+08, 2.2090e+08],
        [2.1474e+08, 2.1055e+08, 2.1191e+08, 2.0900e+08],
        [1.8129e+08, 1.7776e+08, 1.7890e+08, 1.7644e+08],
        [2.041

tensor([[2.0896e+08, 2.0498e+08, 2.0615e+08, 2.0346e+08],
        [2.2034e+08, 2.1615e+08, 2.1738e+08, 2.1455e+08],
        [2.3314e+08, 2.2870e+08, 2.3001e+08, 2.2701e+08],
        [2.1388e+08, 2.0981e+08, 2.1100e+08, 2.0825e+08],
        [2.1325e+08, 2.0919e+08, 2.1039e+08, 2.0764e+08],
        [2.3284e+08, 2.2841e+08, 2.2971e+08, 2.2672e+08],
        [2.0478e+08, 2.0089e+08, 2.0203e+08, 1.9940e+08],
        [2.3047e+05, 2.2608e+05, 2.2737e+05, 2.2440e+05],
        [2.1293e+08, 2.0888e+08, 2.1007e+08, 2.0733e+08],
        [2.7349e+08, 2.6828e+08, 2.6981e+08, 2.6629e+08],
        [2.1730e+08, 2.1317e+08, 2.1438e+08, 2.1159e+08],
        [2.3047e+05, 2.2608e+05, 2.2737e+05, 2.2440e+05],
        [2.0935e+08, 2.0536e+08, 2.0653e+08, 2.0384e+08],
        [2.2456e+08, 2.2029e+08, 2.2155e+08, 2.1866e+08],
        [2.4578e+08, 2.4110e+08, 2.4248e+08, 2.3931e+08],
        [2.1833e+08, 2.1418e+08, 2.1540e+08, 2.1259e+08],
        [2.3047e+05, 2.2608e+05, 2.2737e+05, 2.2440e+05],
        [2.125

tensor([[2.4347e+08, 2.3894e+08, 2.4016e+08, 2.3679e+08],
        [2.4002e+08, 2.3555e+08, 2.3675e+08, 2.3343e+08],
        [2.5966e+05, 2.5484e+05, 2.5613e+05, 2.5254e+05],
        [2.3909e+08, 2.3464e+08, 2.3584e+08, 2.3253e+08],
        [2.5465e+08, 2.4992e+08, 2.5119e+08, 2.4766e+08],
        [2.3819e+08, 2.3376e+08, 2.3495e+08, 2.3165e+08],
        [2.6089e+08, 2.5604e+08, 2.5734e+08, 2.5373e+08],
        [2.5108e+08, 2.4641e+08, 2.4767e+08, 2.4419e+08],
        [2.1500e+08, 2.1100e+08, 2.1208e+08, 2.0910e+08],
        [2.2146e+08, 2.1734e+08, 2.1845e+08, 2.1538e+08],
        [2.3752e+08, 2.3311e+08, 2.3429e+08, 2.3101e+08],
        [2.3533e+08, 2.3096e+08, 2.3213e+08, 2.2888e+08],
        [2.7109e+08, 2.6605e+08, 2.6741e+08, 2.6365e+08],
        [2.4068e+08, 2.3620e+08, 2.3741e+08, 2.3407e+08],
        [2.5966e+05, 2.5484e+05, 2.5613e+05, 2.5254e+05],
        [2.4606e+08, 2.4148e+08, 2.4271e+08, 2.3930e+08],
        [2.4079e+08, 2.3632e+08, 2.3752e+08, 2.3419e+08],
        [2.307

tensor([[2.7365e+08, 2.6873e+08, 2.6983e+08, 2.6591e+08],
        [2.6985e+08, 2.6500e+08, 2.6608e+08, 2.6222e+08],
        [3.1139e+08, 3.0580e+08, 3.0705e+08, 3.0259e+08],
        [2.8337e+08, 2.7828e+08, 2.7942e+08, 2.7536e+08],
        [2.9180e+05, 2.8656e+05, 2.8773e+05, 2.8355e+05],
        [2.4439e+08, 2.4000e+08, 2.4099e+08, 2.3748e+08],
        [2.6373e+08, 2.5899e+08, 2.6005e+08, 2.5627e+08],
        [2.7322e+08, 2.6830e+08, 2.6941e+08, 2.6549e+08],
        [2.6049e+08, 2.5580e+08, 2.5685e+08, 2.5312e+08],
        [2.9180e+05, 2.8656e+05, 2.8773e+05, 2.8355e+05],
        [2.9032e+08, 2.8510e+08, 2.8627e+08, 2.8211e+08],
        [3.1540e+08, 3.0972e+08, 3.1100e+08, 3.0647e+08],
        [2.8877e+08, 2.8358e+08, 2.8475e+08, 2.8061e+08],
        [3.0067e+08, 2.9526e+08, 2.9648e+08, 2.9216e+08],
        [2.7292e+08, 2.6801e+08, 2.6911e+08, 2.6520e+08],
        [2.8759e+08, 2.8242e+08, 2.8358e+08, 2.7946e+08],
        [2.4706e+08, 2.4262e+08, 2.4361e+08, 2.4007e+08],
        [2.650

tensor([[3.0455e+08, 2.9913e+08, 3.0036e+08, 2.9586e+08],
        [3.6162e+08, 3.5519e+08, 3.5665e+08, 3.5130e+08],
        [3.8808e+08, 3.8118e+08, 3.8275e+08, 3.7701e+08],
        [3.1826e+08, 3.1261e+08, 3.1389e+08, 3.0918e+08],
        [3.2697e+05, 3.2116e+05, 3.2248e+05, 3.1764e+05],
        [3.2697e+05, 3.2116e+05, 3.2248e+05, 3.1764e+05],
        [2.7714e+08, 2.7221e+08, 2.7333e+08, 2.6923e+08],
        [2.8800e+08, 2.8288e+08, 2.8405e+08, 2.7979e+08],
        [3.2697e+05, 3.2116e+05, 3.2248e+05, 3.1764e+05],
        [3.0617e+08, 3.0073e+08, 3.0196e+08, 2.9744e+08],
        [3.0239e+08, 2.9702e+08, 2.9824e+08, 2.9377e+08],
        [3.2697e+05, 3.2116e+05, 3.2248e+05, 3.1764e+05],
        [3.0863e+08, 3.0314e+08, 3.0439e+08, 2.9982e+08],
        [2.9680e+08, 2.9153e+08, 2.9272e+08, 2.8833e+08],
        [3.2566e+08, 3.1987e+08, 3.2119e+08, 3.1637e+08],
        [2.8353e+08, 2.7849e+08, 2.7963e+08, 2.7544e+08],
        [3.2697e+05, 3.2116e+05, 3.2248e+05, 3.1764e+05],
        [3.269

tensor([[3.3089e+08, 3.2505e+08, 3.2638e+08, 3.2112e+08],
        [3.1596e+08, 3.1038e+08, 3.1166e+08, 3.0663e+08],
        [3.3848e+08, 3.3251e+08, 3.3387e+08, 3.2848e+08],
        [3.2483e+08, 3.1910e+08, 3.2041e+08, 3.1523e+08],
        [3.7274e+08, 3.6616e+08, 3.6766e+08, 3.6172e+08],
        [3.0947e+08, 3.0401e+08, 3.0525e+08, 3.0033e+08],
        [3.1801e+08, 3.1239e+08, 3.1367e+08, 3.0861e+08],
        [3.1522e+08, 3.0966e+08, 3.1093e+08, 3.0591e+08],
        [3.6543e+05, 3.5898e+05, 3.6046e+05, 3.5464e+05],
        [3.0545e+08, 3.0006e+08, 3.0129e+08, 2.9643e+08],
        [3.4191e+08, 3.3588e+08, 3.3726e+08, 3.3181e+08],
        [3.2238e+08, 3.1669e+08, 3.1799e+08, 3.1285e+08],
        [3.2235e+08, 3.1666e+08, 3.1796e+08, 3.1283e+08],
        [3.3851e+08, 3.3254e+08, 3.3390e+08, 3.2851e+08],
        [3.5318e+08, 3.4694e+08, 3.4837e+08, 3.4275e+08],
        [3.6543e+05, 3.5898e+05, 3.6046e+05, 3.5464e+05],
        [3.6543e+05, 3.5898e+05, 3.6046e+05, 3.5464e+05],
        [3.101

tensor([[4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [3.7564e+08, 3.6930e+08, 3.7058e+08, 3.6397e+08],
        [4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [3.5340e+08, 3.4744e+08, 3.4864e+08, 3.4242e+08],
        [4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [3.4842e+08, 3.4253e+08, 3.4372e+08, 3.3759e+08],
        [3.9447e+08, 3.8781e+08, 3.8915e+08, 3.8221e+08],
        [4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [3.8893e+08, 3.8236e+08, 3.8369e+08, 3.7684e+08],
        [3.7558e+08, 3.6924e+08, 3.7052e+08, 3.6391e+08],
        [4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [4.0727e+05, 4.0040e+05, 4.0179e+05, 3.9462e+05],
        [4.9929e+08, 4.9086e+08, 4.9256e+08, 4.8377e+08],
        [4.0836e+08, 4.0146e+08, 4.0286e+08, 3.9567e+08],
        [3.4967e+08, 3.4377e+08, 3.4497e+08, 3.3881e+08],
        [3.4754e+08, 3.4168e+08, 3.4286e+08, 3.3674e+08],
        [3.944

tensor([[4.2810e+08, 4.2105e+08, 4.2240e+08, 4.1453e+08],
        [3.8980e+08, 3.8339e+08, 3.8462e+08, 3.7745e+08],
        [4.2380e+08, 4.1682e+08, 4.1816e+08, 4.1036e+08],
        [4.7148e+08, 4.6371e+08, 4.6520e+08, 4.5653e+08],
        [3.9364e+08, 3.8716e+08, 3.8840e+08, 3.8116e+08],
        [4.3132e+08, 4.2422e+08, 4.2558e+08, 4.1764e+08],
        [4.0663e+08, 3.9994e+08, 4.0122e+08, 3.9374e+08],
        [4.5282e+05, 4.4537e+05, 4.4680e+05, 4.3847e+05],
        [4.5282e+05, 4.4537e+05, 4.4680e+05, 4.3847e+05],
        [4.2265e+08, 4.1569e+08, 4.1702e+08, 4.0925e+08],
        [4.1896e+08, 4.1207e+08, 4.1339e+08, 4.0568e+08],
        [4.6962e+08, 4.6189e+08, 4.6338e+08, 4.5474e+08],
        [4.5282e+05, 4.4537e+05, 4.4680e+05, 4.3847e+05],
        [4.5282e+05, 4.4537e+05, 4.4680e+05, 4.3847e+05],
        [4.5180e+08, 4.4436e+08, 4.4579e+08, 4.3748e+08],
        [4.4509e+08, 4.3776e+08, 4.3916e+08, 4.3098e+08],
        [4.1387e+08, 4.0706e+08, 4.0837e+08, 4.0075e+08],
        [4.528

tensor([[5.0530e+08, 4.9703e+08, 4.9870e+08, 4.8912e+08],
        [4.6111e+08, 4.5356e+08, 4.5509e+08, 4.4635e+08],
        [4.6502e+08, 4.5741e+08, 4.5895e+08, 4.5014e+08],
        [4.8586e+08, 4.7791e+08, 4.7952e+08, 4.7031e+08],
        [4.7574e+08, 4.6795e+08, 4.6953e+08, 4.6051e+08],
        [5.0235e+05, 4.9413e+05, 4.9579e+05, 4.8627e+05],
        [4.5287e+08, 4.4546e+08, 4.4696e+08, 4.3838e+08],
        [5.0235e+05, 4.9413e+05, 4.9579e+05, 4.8627e+05],
        [4.5604e+08, 4.4857e+08, 4.5008e+08, 4.4144e+08],
        [5.0235e+05, 4.9413e+05, 4.9579e+05, 4.8627e+05],
        [4.5852e+08, 4.5102e+08, 4.5254e+08, 4.4384e+08],
        [4.8692e+08, 4.7895e+08, 4.8056e+08, 4.7133e+08],
        [4.6741e+08, 4.5977e+08, 4.6131e+08, 4.5245e+08],
        [5.0235e+05, 4.9413e+05, 4.9579e+05, 4.8627e+05],
        [5.0235e+05, 4.9413e+05, 4.9579e+05, 4.8627e+05],
        [5.0235e+05, 4.9413e+05, 4.9579e+05, 4.8627e+05],
        [5.5530e+08, 5.4621e+08, 5.4805e+08, 5.3752e+08],
        [4.177

tensor([[5.3922e+08, 5.3047e+08, 5.3164e+08, 5.2167e+08],
        [5.2946e+08, 5.2087e+08, 5.2202e+08, 5.1223e+08],
        [5.0107e+08, 4.9294e+08, 4.9402e+08, 4.8475e+08],
        [4.8314e+08, 4.7530e+08, 4.7634e+08, 4.6741e+08],
        [4.9946e+08, 4.9135e+08, 4.9243e+08, 4.8320e+08],
        [5.5632e+05, 5.4730e+05, 5.4850e+05, 5.3821e+05],
        [5.0273e+08, 4.9457e+08, 4.9566e+08, 4.8636e+08],
        [5.3201e+08, 5.2338e+08, 5.2452e+08, 5.1469e+08],
        [5.2505e+08, 5.1653e+08, 5.1766e+08, 5.0795e+08],
        [5.2982e+08, 5.2122e+08, 5.2237e+08, 5.1257e+08],
        [5.0024e+08, 4.9212e+08, 4.9320e+08, 4.8395e+08],
        [4.6225e+08, 4.5475e+08, 4.5575e+08, 4.4720e+08],
        [5.0237e+08, 4.9422e+08, 4.9530e+08, 4.8601e+08],
        [4.8148e+08, 4.7367e+08, 4.7471e+08, 4.6581e+08],
        [5.2443e+08, 5.1593e+08, 5.1706e+08, 5.0736e+08],
        [5.5632e+05, 5.4730e+05, 5.4850e+05, 5.3821e+05],
        [5.5632e+05, 5.4730e+05, 5.4850e+05, 5.3821e+05],
        [4.894

tensor([[7.4489e+08, 7.3247e+08, 7.3382e+08, 7.2045e+08],
        [6.1510e+05, 6.0485e+05, 6.0597e+05, 5.9492e+05],
        [5.7605e+08, 5.6645e+08, 5.6750e+08, 5.5715e+08],
        [5.3127e+08, 5.2241e+08, 5.2338e+08, 5.1384e+08],
        [5.8539e+08, 5.7562e+08, 5.7669e+08, 5.6618e+08],
        [5.7570e+08, 5.6610e+08, 5.6715e+08, 5.5681e+08],
        [5.7612e+08, 5.6651e+08, 5.6756e+08, 5.5722e+08],
        [5.6784e+08, 5.5837e+08, 5.5941e+08, 5.4921e+08],
        [5.3795e+08, 5.2898e+08, 5.2996e+08, 5.2030e+08],
        [5.8344e+08, 5.7370e+08, 5.7477e+08, 5.6429e+08],
        [5.3391e+08, 5.2501e+08, 5.2598e+08, 5.1639e+08],
        [6.1510e+05, 6.0485e+05, 6.0597e+05, 5.9492e+05],
        [6.1510e+05, 6.0485e+05, 6.0597e+05, 5.9492e+05],
        [5.7910e+08, 5.6944e+08, 5.7049e+08, 5.6009e+08],
        [5.3192e+08, 5.2305e+08, 5.2402e+08, 5.1446e+08],
        [5.6260e+08, 5.5322e+08, 5.5424e+08, 5.4414e+08],
        [5.2575e+08, 5.1698e+08, 5.1793e+08, 5.0849e+08],
        [5.932

tensor([[6.1902e+08, 6.0846e+08, 6.0941e+08, 5.9884e+08],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [6.4656e+08, 6.3553e+08, 6.3652e+08, 6.2549e+08],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [5.8514e+08, 5.7516e+08, 5.7606e+08, 5.6607e+08],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [6.2459e+08, 6.1393e+08, 6.1489e+08, 6.0423e+08],
        [5.9659e+08, 5.8642e+08, 5.8733e+08, 5.7715e+08],
        [6.7404e+08, 6.6254e+08, 6.6357e+08, 6.5207e+08],
        [6.2690e+08, 6.1620e+08, 6.1716e+08, 6.0646e+08],
        [6.7858e+05, 6.6701e+05, 6.6805e+05, 6.5647e+05],
        [6.3311e+08, 6.2231e+08, 6.2328e+08, 6.1248e+08],
        [6.1999e+08, 6.0941e+08, 6.1036e+08, 5.9978e+08],
        [6.3903e+08, 6.2813e+08, 6.2911e+08, 6.1820e+08],
        [6.704

tensor([[7.1197e+08, 6.9937e+08, 7.0062e+08, 6.8903e+08],
        [7.4722e+05, 7.3400e+05, 7.3532e+05, 7.2315e+05],
        [7.0458e+08, 6.9211e+08, 6.9335e+08, 6.8188e+08],
        [7.7581e+08, 7.6207e+08, 7.6344e+08, 7.5081e+08],
        [6.7480e+08, 6.6286e+08, 6.6405e+08, 6.5306e+08],
        [7.2839e+08, 7.1550e+08, 7.1678e+08, 7.0492e+08],
        [7.0048e+08, 6.8808e+08, 6.8932e+08, 6.7791e+08],
        [6.9877e+08, 6.8640e+08, 6.8764e+08, 6.7626e+08],
        [6.9920e+08, 6.8682e+08, 6.8806e+08, 6.7667e+08],
        [6.4931e+08, 6.3782e+08, 6.3896e+08, 6.2839e+08],
        [7.4722e+05, 7.3400e+05, 7.3532e+05, 7.2315e+05],
        [6.3160e+08, 6.2042e+08, 6.2153e+08, 6.1125e+08],
        [6.2791e+08, 6.1680e+08, 6.1791e+08, 6.0768e+08],
        [8.6988e+08, 8.5448e+08, 8.5602e+08, 8.4185e+08],
        [7.0977e+08, 6.9720e+08, 6.9845e+08, 6.8690e+08],
        [7.4722e+05, 7.3400e+05, 7.3532e+05, 7.2315e+05],
        [6.6713e+08, 6.5532e+08, 6.5650e+08, 6.4564e+08],
        [8.020

tensor([[8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [8.9610e+08, 8.7990e+08, 8.8163e+08, 8.6737e+08],
        [8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [7.0756e+08, 6.9477e+08, 6.9614e+08, 6.8488e+08],
        [8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [6.9905e+08, 6.8641e+08, 6.8776e+08, 6.7664e+08],
        [8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [7.6284e+08, 7.4905e+08, 7.5052e+08, 7.3838e+08],
        [8.0082e+08, 7.8634e+08, 7.8789e+08, 7.7515e+08],
        [7.3648e+08, 7.2317e+08, 7.2459e+08, 7.1287e+08],
        [7.8295e+08, 7.6879e+08, 7.7031e+08, 7.5785e+08],
        [8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [8.2127e+05, 8.0642e+05, 8.0801e+05, 7.9494e+05],
        [7.7235e+08, 7.5839e+08, 7.5988e+08, 7.4760e+08],
        [8.2368e+08, 8.0879e+08, 8.1038e+08, 7.9728e+08],
        [7.8384e+08, 7.6968e+08, 7.7119e+08, 7.5872e+08],
        [8.238

tensor([[8.3942e+08, 8.2394e+08, 8.2580e+08, 8.1267e+08],
        [9.0084e+05, 8.8423e+05, 8.8623e+05, 8.7213e+05],
        [8.9287e+08, 8.7640e+08, 8.7839e+08, 8.6442e+08],
        [8.5598e+08, 8.4019e+08, 8.4210e+08, 8.2870e+08],
        [8.4844e+08, 8.3279e+08, 8.3468e+08, 8.2140e+08],
        [7.6928e+08, 7.5510e+08, 7.5681e+08, 7.4477e+08],
        [8.9327e+08, 8.7680e+08, 8.7878e+08, 8.6481e+08],
        [8.5407e+08, 8.3831e+08, 8.4021e+08, 8.2685e+08],
        [7.7547e+08, 7.6117e+08, 7.6289e+08, 7.5076e+08],
        [7.9484e+08, 7.8018e+08, 7.8195e+08, 7.6951e+08],
        [8.3827e+08, 8.2281e+08, 8.2467e+08, 8.1156e+08],
        [9.0084e+05, 8.8423e+05, 8.8623e+05, 8.7213e+05],
        [9.2870e+08, 9.1158e+08, 9.1364e+08, 8.9911e+08],
        [8.8385e+08, 8.6755e+08, 8.6952e+08, 8.5569e+08],
        [8.6822e+08, 8.5221e+08, 8.5414e+08, 8.4056e+08],
        [8.0097e+08, 7.8619e+08, 7.8798e+08, 7.7544e+08],
        [8.4487e+08, 8.2929e+08, 8.3117e+08, 8.1795e+08],
        [8.008

tensor([[9.8650e+05, 9.6793e+05, 9.7058e+05, 9.5546e+05],
        [9.5546e+08, 9.3748e+08, 9.4004e+08, 9.2540e+08],
        [1.0663e+09, 1.0462e+09, 1.0491e+09, 1.0327e+09],
        [9.8650e+05, 9.6793e+05, 9.7058e+05, 9.5546e+05],
        [9.3261e+08, 9.1506e+08, 9.1756e+08, 9.0326e+08],
        [9.7694e+08, 9.5856e+08, 9.6118e+08, 9.4620e+08],
        [9.7959e+08, 9.6115e+08, 9.6378e+08, 9.4876e+08],
        [9.2556e+08, 9.0814e+08, 9.1063e+08, 8.9644e+08],
        [9.3027e+08, 9.1276e+08, 9.1526e+08, 9.0100e+08],
        [9.7120e+08, 9.5292e+08, 9.5553e+08, 9.4064e+08],
        [8.3257e+08, 8.1690e+08, 8.1914e+08, 8.0637e+08],
        [8.8737e+08, 8.7067e+08, 8.7305e+08, 8.5945e+08],
        [9.3882e+08, 9.2115e+08, 9.2368e+08, 9.0928e+08],
        [9.8650e+05, 9.6793e+05, 9.7058e+05, 9.5546e+05],
        [1.0012e+09, 9.8232e+08, 9.8501e+08, 9.6966e+08],
        [9.4144e+08, 9.2372e+08, 9.2625e+08, 9.1181e+08],
        [1.2171e+09, 1.1942e+09, 1.1975e+09, 1.1788e+09],
        [9.865

tensor([[1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [1.1200e+09, 1.0988e+09, 1.1024e+09, 1.0845e+09],
        [1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [9.5604e+08, 9.3798e+08, 9.4101e+08, 9.2576e+08],
        [1.3000e+09, 1.2755e+09, 1.2796e+09, 1.2589e+09],
        [1.0041e+09, 9.8509e+08, 9.8827e+08, 9.7225e+08],
        [9.8834e+08, 9.6967e+08, 9.7280e+08, 9.5704e+08],
        [1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [9.1339e+08, 8.9614e+08, 8.9903e+08, 8.8446e+08],
        [1.1315e+09, 1.1102e+09, 1.1137e+09, 1.0957e+09],
        [1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [1.0785e+06, 1.0581e+06, 1.0616e+06, 1.0444e+06],
        [9.7543e+08, 9.5700e+08, 9.6009e+08, 9.4453e+08],
        [1.0239e+09, 1.0046e+09, 1.0078e+09, 9.9150e+08],
        [9.8296e+08, 9.6440e+08, 9.6751e+08, 9.5183e+08],
        [1.078

tensor([[1.1193e+09, 1.0981e+09, 1.1024e+09, 1.0837e+09],
        [1.1315e+09, 1.1101e+09, 1.1144e+09, 1.0955e+09],
        [1.1762e+06, 1.1540e+06, 1.1585e+06, 1.1388e+06],
        [1.1215e+09, 1.1003e+09, 1.1045e+09, 1.0858e+09],
        [1.1121e+09, 1.0911e+09, 1.0953e+09, 1.0767e+09],
        [1.1762e+06, 1.1540e+06, 1.1585e+06, 1.1388e+06],
        [1.0687e+09, 1.0485e+09, 1.0525e+09, 1.0347e+09],
        [1.1048e+09, 1.0839e+09, 1.0881e+09, 1.0696e+09],
        [1.1275e+09, 1.1062e+09, 1.1105e+09, 1.0917e+09],
        [1.2257e+09, 1.2025e+09, 1.2072e+09, 1.1867e+09],
        [1.1762e+06, 1.1540e+06, 1.1585e+06, 1.1388e+06],
        [1.0454e+09, 1.0256e+09, 1.0296e+09, 1.0121e+09],
        [1.1358e+09, 1.1144e+09, 1.1187e+09, 1.0997e+09],
        [1.1861e+09, 1.1637e+09, 1.1682e+09, 1.1484e+09],
        [1.2161e+09, 1.1931e+09, 1.1978e+09, 1.1774e+09],
        [1.1709e+09, 1.1488e+09, 1.1532e+09, 1.1337e+09],
        [1.2697e+09, 1.2457e+09, 1.2505e+09, 1.2293e+09],
        [1.008

tensor([[1.0737e+09, 1.0534e+09, 1.0583e+09, 1.0397e+09],
        [1.1788e+09, 1.1565e+09, 1.1619e+09, 1.1415e+09],
        [1.2808e+06, 1.2566e+06, 1.2624e+06, 1.2403e+06],
        [1.2808e+06, 1.2566e+06, 1.2624e+06, 1.2403e+06],
        [1.2543e+09, 1.2306e+09, 1.2363e+09, 1.2146e+09],
        [1.2808e+06, 1.2566e+06, 1.2624e+06, 1.2403e+06],
        [1.3663e+09, 1.3404e+09, 1.3467e+09, 1.3231e+09],
        [1.1762e+09, 1.1539e+09, 1.1593e+09, 1.1390e+09],
        [1.3019e+09, 1.2773e+09, 1.2832e+09, 1.2607e+09],
        [1.0896e+09, 1.0690e+09, 1.0739e+09, 1.0551e+09],
        [1.2808e+06, 1.2566e+06, 1.2624e+06, 1.2403e+06],
        [1.2808e+06, 1.2566e+06, 1.2624e+06, 1.2403e+06],
        [1.2701e+09, 1.2461e+09, 1.2519e+09, 1.2299e+09],
        [1.1026e+09, 1.0817e+09, 1.0868e+09, 1.0677e+09],
        [1.2242e+09, 1.2010e+09, 1.2066e+09, 1.1854e+09],
        [1.0989e+09, 1.0781e+09, 1.0831e+09, 1.0641e+09],
        [1.1485e+09, 1.1268e+09, 1.1320e+09, 1.1122e+09],
        [1.187

tensor([[1.3402e+09, 1.3148e+09, 1.3218e+09, 1.2974e+09],
        [1.3760e+09, 1.3499e+09, 1.3571e+09, 1.3320e+09],
        [1.3934e+06, 1.3670e+06, 1.3742e+06, 1.3489e+06],
        [1.2212e+09, 1.1981e+09, 1.2044e+09, 1.1822e+09],
        [1.2685e+09, 1.2445e+09, 1.2511e+09, 1.2281e+09],
        [1.1598e+09, 1.1378e+09, 1.1438e+09, 1.1227e+09],
        [1.2981e+09, 1.2735e+09, 1.2803e+09, 1.2567e+09],
        [1.1644e+09, 1.1424e+09, 1.1484e+09, 1.1272e+09],
        [1.3612e+09, 1.3355e+09, 1.3425e+09, 1.3178e+09],
        [1.2508e+09, 1.2271e+09, 1.2336e+09, 1.2109e+09],
        [1.3706e+09, 1.3446e+09, 1.3517e+09, 1.3268e+09],
        [1.1954e+09, 1.1728e+09, 1.1790e+09, 1.1573e+09],
        [1.2711e+09, 1.2470e+09, 1.2536e+09, 1.2305e+09],
        [1.7219e+09, 1.6893e+09, 1.6982e+09, 1.6669e+09],
        [1.2405e+09, 1.2171e+09, 1.2235e+09, 1.2010e+09],
        [1.3167e+09, 1.2918e+09, 1.2987e+09, 1.2747e+09],
        [1.3192e+09, 1.2943e+09, 1.3011e+09, 1.2771e+09],
        [1.393

tensor([[1.3247e+09, 1.2999e+09, 1.3073e+09, 1.2815e+09],
        [1.4461e+09, 1.4190e+09, 1.4271e+09, 1.3989e+09],
        [1.3981e+09, 1.3719e+09, 1.3797e+09, 1.3524e+09],
        [1.3161e+09, 1.2915e+09, 1.2988e+09, 1.2731e+09],
        [1.3982e+09, 1.3720e+09, 1.3798e+09, 1.3525e+09],
        [1.4430e+09, 1.4160e+09, 1.4241e+09, 1.3959e+09],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.3184e+09, 1.2937e+09, 1.3010e+09, 1.2753e+09],
        [1.4517e+09, 1.4245e+09, 1.4326e+09, 1.4043e+09],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.4238e+09, 1.3972e+09, 1.4051e+09, 1.3773e+09],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.3211e+09, 1.2964e+09, 1.3038e+09, 1.2780e+09],
        [1.5140e+06, 1.4857e+06, 1.4941e+06, 1.4646e+06],
        [1.398

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/home/jonne/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-4db53a9792d4>", line 2, in <module>
    rvc.fit(data)
  File "<ipython-input-5-191abb44f50f>", line 22, in fit
    train.train(self.model, self.optimizer, train_loader, self.kwargs['loss_func'], self.kwargs['log_step'], self.device)
  File "/home/jonne/Documents/Master_thesis/utils/train_utils.py", line 23, in train
    optimizer.step()
  File "/home/jonne/anaconda3/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/jonne/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/jonne/anaconda3/lib/python3.8/site-packages/torch/optim/adam.py", line 133, in step
    F.adam(params_with_grad,
  File "/home/jo

TypeError: object of type 'NoneType' has no len()